//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeeftSamen.Common.InterfaceText {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Alert {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Alert() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeeftSamen.Common.InterfaceText.Alert", typeof(Alert).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Helaas, deze actie is inmiddels afgelopen..
        /// </summary>
        public static string ActionExpired {
            get {
                return ResourceManager.GetString("ActionExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} activiteiten aangemaakt.
        /// </summary>
        public static string ActivitiesCreated {
            get {
                return ResourceManager.GetString("ActivitiesCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bent nu aangemeld voor de activiteit &apos;{0}&apos;..
        /// </summary>
        public static string ActivityAttending {
            get {
                return ResourceManager.GetString("ActivityAttending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De activiteit is aangemaakt..
        /// </summary>
        public static string ActivityCreated {
            get {
                return ResourceManager.GetString("ActivityCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De uitnodiging voor deze activiteit is verlopen..
        /// </summary>
        public static string ActivityInvitationExpired {
            get {
                return ResourceManager.GetString("ActivityInvitationExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bent nu afgemeld voor de activiteit &apos;{0}&apos;..
        /// </summary>
        public static string ActivityNotAttending {
            get {
                return ResourceManager.GetString("ActivityNotAttending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode succesvol toegevoegd.
        /// </summary>
        public static string AddZipCodeSuccess {
            get {
                return ResourceManager.GetString("AddZipCodeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je verzoek om lid te worden van de kring is verstuurd naar de beheerders van de kring. Zij bepalen of je lid kunt worden van de kring..
        /// </summary>
        public static string AskToJoinCircleSuccess {
            get {
                return ResourceManager.GetString("AskToJoinCircleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het fotoalbum kon niet aangemaakt worden..
        /// </summary>
        public static string CantCreatePhotoAlbum {
            get {
                return ResourceManager.GetString("CantCreatePhotoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je e-mailinstellingen zijn gewijzigd..
        /// </summary>
        public static string ChangeEmailSettingsSuccess {
            get {
                return ResourceManager.GetString("ChangeEmailSettingsSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foruminstellingen zijn gewijzigd..
        /// </summary>
        public static string ChangeForumSuccess {
            get {
                return ResourceManager.GetString("ChangeForumSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je naam is gewijzigd..
        /// </summary>
        public static string ChangeNameSuccess {
            get {
                return ResourceManager.GetString("ChangeNameSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je buurt is gewijzigd..
        /// </summary>
        public static string ChangeNeighborhoodSuccess {
            get {
                return ResourceManager.GetString("ChangeNeighborhoodSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je wachtwoord is gewijzigd..
        /// </summary>
        public static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je profielfoto is gewijzigd..
        /// </summary>
        public static string ChangeProfilePictureSuccess {
            get {
                return ResourceManager.GetString("ChangeProfilePictureSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je e-mailadres is gewijzigd..
        /// </summary>
        public static string ChangeUsernameSuccess {
            get {
                return ResourceManager.GetString("ChangeUsernameSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De kring is aangemaakt..
        /// </summary>
        public static string CircleCreated {
            get {
                return ResourceManager.GetString("CircleCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De {0} documenten zijn geplaatst..
        /// </summary>
        public static string CircleDocsUploaded {
            get {
                return ResourceManager.GetString("CircleDocsUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt het document verwijderd..
        /// </summary>
        public static string CircleDocumentRemoved {
            get {
                return ResourceManager.GetString("CircleDocumentRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je document is geplaatst..
        /// </summary>
        public static string CircleDocUploaded {
            get {
                return ResourceManager.GetString("CircleDocUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bent uit het gesprek verwijderd.
        /// </summary>
        public static string CircleEmailGroupRemoved {
            get {
                return ResourceManager.GetString("CircleEmailGroupRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bericht is geplaatst..
        /// </summary>
        public static string CircleMessageCreated {
            get {
                return ResourceManager.GetString("CircleMessageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het bericht is verwijderd..
        /// </summary>
        public static string CircleMessageDeleted {
            get {
                return ResourceManager.GetString("CircleMessageDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bericht is successvol gewijzigd..
        /// </summary>
        public static string CircleMessageEdited {
            get {
                return ResourceManager.GetString("CircleMessageEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bericht moet minstens 1 karakter lang zijn..
        /// </summary>
        public static string CircleMessageEditEmpy {
            get {
                return ResourceManager.GetString("CircleMessageEditEmpy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is langer dan 10 minuten verstreken. Je kunt je bericht niet langer aanpassen..
        /// </summary>
        public static string CircleMessageEditTimeExpired {
            get {
                return ResourceManager.GetString("CircleMessageEditTimeExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je reactie is geplaatst..
        /// </summary>
        public static string CircleMessageReactionCreated {
            get {
                return ResourceManager.GetString("CircleMessageReactionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt het fotoalbum {0} aangemaakt..
        /// </summary>
        public static string CirclePhotoAlbumCreated {
            get {
                return ResourceManager.GetString("CirclePhotoAlbumCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt het fotoalbum {0} verwijderd..
        /// </summary>
        public static string CirclePhotoAlbumRemoved {
            get {
                return ResourceManager.GetString("CirclePhotoAlbumRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt de foto verwijderd..
        /// </summary>
        public static string CirclePhotoRemoved {
            get {
                return ResourceManager.GetString("CirclePhotoRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De {0} foto&apos;s zijn geplaatst..
        /// </summary>
        public static string CirclePhotosUploaded {
            get {
                return ResourceManager.GetString("CirclePhotosUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je foto is geplaatst..
        /// </summary>
        public static string CirclePhotoUploaded {
            get {
                return ResourceManager.GetString("CirclePhotoUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} heeft nu beheerrechten voor de kring..
        /// </summary>
        public static string CircleUserAdminGiven {
            get {
                return ResourceManager.GetString("CircleUserAdminGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De beheerrechten voor de kring van {0} zijn ingetrokken..
        /// </summary>
        public static string CircleUserAdminRevoked {
            get {
                return ResourceManager.GetString("CircleUserAdminRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je ontvangt weer emails van deze kring.
        /// </summary>
        public static string CircleUserEmailStarted {
            get {
                return ResourceManager.GetString("CircleUserEmailStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je ontvangt niet langer meer emails van deze kring.
        /// </summary>
        public static string CircleUserEmailStopped {
            get {
                return ResourceManager.GetString("CircleUserEmailStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt de uitnodiging geweigerd..
        /// </summary>
        public static string DeclinedCircleRequest {
            get {
                return ResourceManager.GetString("DeclinedCircleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je plaatst nu berichten met je persoonlijke profiel..
        /// </summary>
        public static string DeselectOrganizationSuccess {
            get {
                return ResourceManager.GetString("DeselectOrganizationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je e-mailadres is bevestigd..
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jouw vraag is doorgestuurd naar je buren!.
        /// </summary>
        public static string HelpMarketplaceItem {
            get {
                return ResourceManager.GetString("HelpMarketplaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongeldig bestandstype geupload.
        /// </summary>
        public static string IncorrectFileType {
            get {
                return ResourceManager.GetString("IncorrectFileType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt de uitnodiging van de kring &apos;{0}&apos; geweigerd..
        /// </summary>
        public static string InvitationRejected {
            get {
                return ResourceManager.GetString("InvitationRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De taak is aan je toegekend..
        /// </summary>
        public static string JobAssignedToCurrentUser {
            get {
                return ResourceManager.GetString("JobAssignedToCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super leuk dat je dit wilde doen, maar iemand anders heeft deze al opgepakt.
        /// </summary>
        public static string JobAssignedToOtherUser {
            get {
                return ResourceManager.GetString("JobAssignedToOtherUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De taak is aangemaakt..
        /// </summary>
        public static string JobCreated {
            get {
                return ResourceManager.GetString("JobCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je taak is aangepast.
        /// </summary>
        public static string JobEdited {
            get {
                return ResourceManager.GetString("JobEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De taak is verwijderd..
        /// </summary>
        public static string JobRemoved {
            get {
                return ResourceManager.GetString("JobRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De taak is weer vrijgegeven..
        /// </summary>
        public static string JobUnassigned {
            get {
                return ResourceManager.GetString("JobUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het verzoek is goedgekeurd..
        /// </summary>
        public static string JoinRequestAccepted {
            get {
                return ResourceManager.GetString("JoinRequestAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het verzoek is afgewezen..
        /// </summary>
        public static string JoinRequestRejected {
            get {
                return ResourceManager.GetString("JoinRequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt de kring verlaten..
        /// </summary>
        public static string LeaveCircleSuccess {
            get {
                return ResourceManager.GetString("LeaveCircleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jouw vraag is doorgestuurd naar je buren!.
        /// </summary>
        public static string LendMarketplaceItem {
            get {
                return ResourceManager.GetString("LendMarketplaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bent nu ingelogd..
        /// </summary>
        public static string LoginSuccess {
            get {
                return ResourceManager.GetString("LoginSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Groep aangemaakt..
        /// </summary>
        public static string MessageGroupCreatedSuccess {
            get {
                return ResourceManager.GetString("MessageGroupCreatedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het bericht is uit &apos;Postvak IN&apos; verwijderd.
        /// </summary>
        public static string MessageRemovedFromInbox {
            get {
                return ResourceManager.GetString("MessageRemovedFromInbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het bericht is uit &apos;Verzonden berichten&apos; verwijderd.
        /// </summary>
        public static string MessageRemovedFromSend {
            get {
                return ResourceManager.GetString("MessageRemovedFromSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het bericht is verzonden!.
        /// </summary>
        public static string MessageSendSuccess {
            get {
                return ResourceManager.GetString("MessageSendSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je reactie is geplaatst..
        /// </summary>
        public static string NeighborhoodMessageReactionCreated {
            get {
                return ResourceManager.GetString("NeighborhoodMessageReactionCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bent nog beheerder van de volgende kringen: {0}. Verwijder eerst deze kringen of maak iemand anders beheerder..
        /// </summary>
        public static string OnlyAdminOfCircle {
            get {
                return ResourceManager.GetString("OnlyAdminOfCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De gegevens van de organisatie zijn aangepast..
        /// </summary>
        public static string OrganizationEditSuccess {
            get {
                return ResourceManager.GetString("OrganizationEditSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De aanvraag is ingediend. Een beheerder van LeeftSamen zal de aanvraag zo spoedig mogelijk in behandeling nemen..
        /// </summary>
        public static string OrganizationRequestSuccess {
            get {
                return ResourceManager.GetString("OrganizationRequestSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} heeft nu beheerrechten voor de organisatie..
        /// </summary>
        public static string OrganizationUserAdminGiven {
            get {
                return ResourceManager.GetString("OrganizationUserAdminGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De beheerrechten voor de organisatie van {0} zijn ingetrokken..
        /// </summary>
        public static string OrganizationUserAdminRevoked {
            get {
                return ResourceManager.GetString("OrganizationUserAdminRevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je account is verwijderd..
        /// </summary>
        public static string RemoveAccountSuccess {
            get {
                return ResourceManager.GetString("RemoveAccountSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De beheerder is uit het buurtplein verwijderd..
        /// </summary>
        public static string RemoveAdminFromSquareSuccess {
            get {
                return ResourceManager.GetString("RemoveAdminFromSquareSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De kring is verwijderd..
        /// </summary>
        public static string RemoveCircleSuccess {
            get {
                return ResourceManager.GetString("RemoveCircleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het feit is verwijderd..
        /// </summary>
        public static string RemoveFactSuccess {
            get {
                return ResourceManager.GetString("RemoveFactSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het kringlid is uit de kring verwijderd..
        /// </summary>
        public static string RemoveMemberFromCircleSuccess {
            get {
                return ResourceManager.GetString("RemoveMemberFromCircleSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De medewerker is verwijderd..
        /// </summary>
        public static string RemoveMemberFromOrganizationSuccess {
            get {
                return ResourceManager.GetString("RemoveMemberFromOrganizationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerapporteerde reactie genegeerd.
        /// </summary>
        public static string RemoveReactionReportSuccess {
            get {
                return ResourceManager.GetString("RemoveReactionReportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De reactie is verwijderd.
        /// </summary>
        public static string RemoveReactionSuccess {
            get {
                return ResourceManager.GetString("RemoveReactionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het onderwerp is verwijderd.
        /// </summary>
        public static string RemoveSubjectSuccess {
            get {
                return ResourceManager.GetString("RemoveSubjectSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De postcode is verwijderd..
        /// </summary>
        public static string RemoveZipCodeSuccess {
            get {
                return ResourceManager.GetString("RemoveZipCodeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je melding van misbruik is verzonden. We nemen deze serieus en zullen deze zo snel mogelijk behandelen..
        /// </summary>
        public static string ReportAbuseReported {
            get {
                return ResourceManager.GetString("ReportAbuseReported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De reactie is gerapporteerd.
        /// </summary>
        public static string ReportReactionSuccess {
            get {
                return ResourceManager.GetString("ReportReactionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je wachtwoord is gewijzigd..
        /// </summary>
        public static string ResetPasswordSuccess {
            get {
                return ResourceManager.GetString("ResetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je plaatst nu berichten als medewerker van {0}..
        /// </summary>
        public static string SelectOrganizationSuccess {
            get {
                return ResourceManager.GetString("SelectOrganizationSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De kring is nu privé..
        /// </summary>
        public static string SetCirclePrivateSuccess {
            get {
                return ResourceManager.GetString("SetCirclePrivateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De kring is nu openbaar..
        /// </summary>
        public static string SetCirclePublicSuccess {
            get {
                return ResourceManager.GetString("SetCirclePublicSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je suggestie is verzonden naar het LeeftSamen-team. Bedankt!.
        /// </summary>
        public static string SuggestionSend {
            get {
                return ResourceManager.GetString("SuggestionSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt {0} uitgenodigd om mee te doen met jouw activiteit..
        /// </summary>
        public static string UserInvitedForActivity {
            get {
                return ResourceManager.GetString("UserInvitedForActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt {0} uitgenodigd om mee te doen met een activiteit. De uitnodiging wordt verstuurd via e-mail..
        /// </summary>
        public static string UserIsInvitedForTheActivityByEmail {
            get {
                return ResourceManager.GetString("UserIsInvitedForTheActivityByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt {0} succesvol uitgenodigd om toe te treden tot je kring. {0} ontvangt een e-mail met je uitnodiging..
        /// </summary>
        public static string UserIsInvitedForTheCircle {
            get {
                return ResourceManager.GetString("UserIsInvitedForTheCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt {0} succesvol uitgenodigd om toe te treden tot je organisatie. {0} ontvangt een e-mail met je uitnodiging..
        /// </summary>
        public static string UserIsInvitedForTheOrganization {
            get {
                return ResourceManager.GetString("UserIsInvitedForTheOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt {0} succesvol toegevoegd als beheerder van dit buurtplein..
        /// </summary>
        public static string UserIsInvitedForTheSquare {
            get {
                return ResourceManager.GetString("UserIsInvitedForTheSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets mis gegaan met het versturen van de uitnodigingen, probeer het later opnieuw..
        /// </summary>
        public static string UsersInvitedByEmailFailed {
            get {
                return ResourceManager.GetString("UsersInvitedByEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als medewerker kan je geen mensen uitnodigen voor deze activiteit..
        /// </summary>
        public static string UsersInvitedByOrganizationUserFailed {
            get {
                return ResourceManager.GetString("UsersInvitedByOrganizationUserFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt {0} uitgenodigd om toe te treden tot je kring. De uitnodiging wordt verstuurd via e-mail..
        /// </summary>
        public static string UsersInvitedForTheCircleByEmail {
            get {
                return ResourceManager.GetString("UsersInvitedForTheCircleByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt {0} uitgenodigd om toe te treden tot je organisatie. De uitnodiging wordt verstuurd via e-mail..
        /// </summary>
        public static string UsersInvitedForTheOrganizationByEmail {
            get {
                return ResourceManager.GetString("UsersInvitedForTheOrganizationByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De uitnodiging is succesvol verzonden.
        /// </summary>
        public static string UsersInvitedforWebsite {
            get {
                return ResourceManager.GetString("UsersInvitedforWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je stem kon niet verwerkt worden..
        /// </summary>
        public static string VoteActionFailure {
            get {
                return ResourceManager.GetString("VoteActionFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bedankt voor jouw stem..
        /// </summary>
        public static string VoteActionSuccess {
            get {
                return ResourceManager.GetString("VoteActionSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bent nu lid van de kring &apos;{0}&apos;..
        /// </summary>
        public static string YouAreNowACircleMember {
            get {
                return ResourceManager.GetString("YouAreNowACircleMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bent nu lid van de organisatie &apos;{0}&apos;..
        /// </summary>
        public static string YouAreNowAOrganizationMember {
            get {
                return ResourceManager.GetString("YouAreNowAOrganizationMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jouw zuiderling account is gekoppeld..
        /// </summary>
        public static string ZuiderlingAccountLinked {
            get {
                return ResourceManager.GetString("ZuiderlingAccountLinked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze transactie overschrijdt het dagelijkse overmaaklimiet van jouw account..
        /// </summary>
        public static string ZuiderlingTransactionDailyLimit {
            get {
                return ResourceManager.GetString("ZuiderlingTransactionDailyLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is iets fout gegaan bij de transactie..
        /// </summary>
        public static string ZuiderlingTransactionError {
            get {
                return ResourceManager.GetString("ZuiderlingTransactionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De ontvanger kan op dit moment deze hoeveelheid zuiderlingen niet meer ontvangen..
        /// </summary>
        public static string ZuiderlingTransactionReceiverLimit {
            get {
                return ResourceManager.GetString("ZuiderlingTransactionReceiverLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jouw account heeft niet meer genoeg zuiderlingen voor deze transactie..
        /// </summary>
        public static string ZuiderlingTransactionShortage {
            get {
                return ResourceManager.GetString("ZuiderlingTransactionShortage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuiderlingen overgemaakt.
        /// </summary>
        public static string ZuiderlingTransactionSuccess {
            get {
                return ResourceManager.GetString("ZuiderlingTransactionSuccess", resourceCulture);
            }
        }
    }
}
