//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeeftSamen.Common.InterfaceText {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Button {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Button() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeeftSamen.Common.InterfaceText.Button", typeof(Button).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over LeeftSamen.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepteren.
        /// </summary>
        public static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitnodiging accepteren.
        /// </summary>
        public static string AcceptInvite {
            get {
                return ResourceManager.GetString("AcceptInvite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actie nog niet begonnen.
        /// </summary>
        public static string ActionNotStarted {
            get {
                return ResourceManager.GetString("ActionNotStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actie afgelopen.
        /// </summary>
        public static string ActionOver {
            get {
                return ResourceManager.GetString("ActionOver", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteiten.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door mij georganiseerd.
        /// </summary>
        public static string ActivitiesSelfOrganized {
            get {
                return ResourceManager.GetString("ActivitiesSelfOrganized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aankomende activiteiten.
        /// </summary>
        public static string ActivitiesUpcoming {
            get {
                return ResourceManager.GetString("ActivitiesUpcoming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toevoegen.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteit toevoegen.
        /// </summary>
        public static string AddActivity {
            get {
                return ResourceManager.GetString("AddActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beheerders toevoegen.
        /// </summary>
        public static string AddAdmins {
            get {
                return ResourceManager.GetString("AddAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum toevoegen.
        /// </summary>
        public static string AddDate {
            get {
                return ResourceManager.GetString("AddDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voeg documenten toe.
        /// </summary>
        public static string AddDocuments {
            get {
                return ResourceManager.GetString("AddDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voeg een foto toe.
        /// </summary>
        public static string AddPhoto {
            get {
                return ResourceManager.GetString("AddPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Koppel account.
        /// </summary>
        public static string AddZuiderlingAccount {
            get {
                return ResourceManager.GetString("AddZuiderlingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beheerders.
        /// </summary>
        public static string Admins {
            get {
                return ResourceManager.GetString("Admins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string Agenda {
            get {
                return ResourceManager.GetString("Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle leden.
        /// </summary>
        public static string AllMembers {
            get {
                return ResourceManager.GetString("AllMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle berichten.
        /// </summary>
        public static string AllMessages {
            get {
                return ResourceManager.GetString("AllMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik ga het doen!.
        /// </summary>
        public static string AssignJobToMe {
            get {
                return ResourceManager.GetString("AssignJobToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verenigingen.
        /// </summary>
        public static string AssociationMessages {
            get {
                return ResourceManager.GetString("AssociationMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik ben erbij!.
        /// </summary>
        public static string AttendingActivity {
            get {
                return ResourceManager.GetString("AttendingActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terug naar overzicht.
        /// </summary>
        public static string BackToOverview {
            get {
                return ResourceManager.GetString("BackToOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buddy worden.
        /// </summary>
        public static string BecomeBuddy {
            get {
                return ResourceManager.GetString("BecomeBuddy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lid worden.
        /// </summary>
        public static string BecomeMember {
            get {
                return ResourceManager.GetString("BecomeMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuleren.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail instellingen wijzigen.
        /// </summary>
        public static string ChangeEmailSettings {
            get {
                return ResourceManager.GetString("ChangeEmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foruminstellingen wijzigen.
        /// </summary>
        public static string ChangeForum {
            get {
                return ResourceManager.GetString("ChangeForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algemene instellingen wijzigen.
        /// </summary>
        public static string ChangeGeneral {
            get {
                return ResourceManager.GetString("ChangeGeneral", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig je naam.
        /// </summary>
        public static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buurtinstellingen wijzigen.
        /// </summary>
        public static string ChangeNeighborhood {
            get {
                return ResourceManager.GetString("ChangeNeighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificatie instellingen wijzigen.
        /// </summary>
        public static string ChangeNotifications {
            get {
                return ResourceManager.GetString("ChangeNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig je wachtwoord.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig je profielfoto.
        /// </summary>
        public static string ChangeProfileImage {
            get {
                return ResourceManager.GetString("ChangeProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig je e-mailadres.
        /// </summary>
        public static string ChangeUsername {
            get {
                return ResourceManager.GetString("ChangeUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toegestane postcodes wijzigen.
        /// </summary>
        public static string ChangeZipCodes {
            get {
                return ResourceManager.GetString("ChangeZipCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuiderling account koppelen.
        /// </summary>
        public static string ChangeZuiderlingAccount {
            get {
                return ResourceManager.GetString("ChangeZuiderlingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies een bestand.
        /// </summary>
        public static string ChooseFileFromPC {
            get {
                return ResourceManager.GetString("ChooseFileFromPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies een afbeelding.
        /// </summary>
        public static string ChooseImageFromPC {
            get {
                return ResourceManager.GetString("ChooseImageFromPC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kringen.
        /// </summary>
        public static string Circles {
            get {
                return ResourceManager.GetString("Circles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Klik hier om in te loggen.
        /// </summary>
        public static string ClickToLogin {
            get {
                return ResourceManager.GetString("ClickToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sluiten.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact.
        /// </summary>
        public static string Contact {
            get {
                return ResourceManager.GetString("Contact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak je profiel aan!.
        /// </summary>
        public static string CreateAccount {
            get {
                return ResourceManager.GetString("CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meerdere activiteiten aanmaken.
        /// </summary>
        public static string CreateActivities {
            get {
                return ResourceManager.GetString("CreateActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe activiteit.
        /// </summary>
        public static string CreateActivity {
            get {
                return ResourceManager.GetString("CreateActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe kring.
        /// </summary>
        public static string CreateCircle {
            get {
                return ResourceManager.GetString("CreateCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feit toevoegen.
        /// </summary>
        public static string CreateFact {
            get {
                return ResourceManager.GetString("CreateFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw onderwerp.
        /// </summary>
        public static string CreateForumSubject {
            get {
                return ResourceManager.GetString("CreateForumSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak gesprek aan.
        /// </summary>
        public static string CreateGroup {
            get {
                return ResourceManager.GetString("CreateGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe taak.
        /// </summary>
        public static string CreateJob {
            get {
                return ResourceManager.GetString("CreateJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe advertentie.
        /// </summary>
        public static string CreateMarketplaceItem {
            get {
                return ResourceManager.GetString("CreateMarketplaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burenhulp aanbieden.
        /// </summary>
        public static string CreateMarketplaceItemHelp {
            get {
                return ResourceManager.GetString("CreateMarketplaceItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw nieuwsbericht.
        /// </summary>
        public static string CreateNeighborhoodMessage {
            get {
                return ResourceManager.GetString("CreateNeighborhoodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe taak plaatsen.
        /// </summary>
        public static string CreateNewJob {
            get {
                return ResourceManager.GetString("CreateNewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak een fotoalbum aan.
        /// </summary>
        public static string CreatePhotoAlbum {
            get {
                return ResourceManager.GetString("CreatePhotoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weigeren.
        /// </summary>
        public static string Decline {
            get {
                return ResourceManager.GetString("Decline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze organisatie verwijderen.
        /// </summary>
        public static string DeleteOrganization {
            get {
                return ResourceManager.GetString("DeleteOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze reactie verwijderen.
        /// </summary>
        public static string DeleteReaction {
            get {
                return ResourceManager.GetString("DeleteReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit onderwerp verwijderen.
        /// </summary>
        public static string DeleteSubject {
            get {
                return ResourceManager.GetString("DeleteSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontdek LeeftSamen.
        /// </summary>
        public static string DiscoverPlatform {
            get {
                return ResourceManager.GetString("DiscoverPlatform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Docs.
        /// </summary>
        public static string Documents {
            get {
                return ResourceManager.GetString("Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download alle bijlagen.
        /// </summary>
        public static string DownloadAllAttachments {
            get {
                return ResourceManager.GetString("DownloadAllAttachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze activiteit wijzigen.
        /// </summary>
        public static string EditActivity {
            get {
                return ResourceManager.GetString("EditActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze kring wijzigen.
        /// </summary>
        public static string EditCircle {
            get {
                return ResourceManager.GetString("EditCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit feit wijzigen.
        /// </summary>
        public static string EditFact {
            get {
                return ResourceManager.GetString("EditFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze taak wijzigen.
        /// </summary>
        public static string EditJob {
            get {
                return ResourceManager.GetString("EditJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze advertentie wijzigen.
        /// </summary>
        public static string EditMarketplaceItem {
            get {
                return ResourceManager.GetString("EditMarketplaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        public static string EditMessage {
            get {
                return ResourceManager.GetString("EditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit nieuwsbericht wijzigen.
        /// </summary>
        public static string EditNeighborhoodMessage {
            get {
                return ResourceManager.GetString("EditNeighborhoodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze organisatie wijzigen.
        /// </summary>
        public static string EditOrganization {
            get {
                return ResourceManager.GetString("EditOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze reactie wijzigen.
        /// </summary>
        public static string EditReaction {
            get {
                return ResourceManager.GetString("EditReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit buurtplein wijzigen.
        /// </summary>
        public static string EditSquare {
            get {
                return ResourceManager.GetString("EditSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit onderwerp wijzigen.
        /// </summary>
        public static string EditSubject {
            get {
                return ResourceManager.GetString("EditSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feiten.
        /// </summary>
        public static string Facts {
            get {
                return ResourceManager.GetString("Facts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voltooien.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord vergeten.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        public static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reageren.
        /// </summary>
        public static string ForumReact {
            get {
                return ResourceManager.GetString("ForumReact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beheerrechten geven.
        /// </summary>
        public static string GiveMemberAdminRights {
            get {
                return ResourceManager.GetString("GiveMemberAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestie indienen.
        /// </summary>
        public static string GiveSuggestion {
            get {
                return ResourceManager.GetString("GiveSuggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt al gestemd.
        /// </summary>
        public static string HasVoted {
            get {
                return ResourceManager.GetString("HasVoted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactie is oké.
        /// </summary>
        public static string IgnoreReportedReaction {
            get {
                return ResourceManager.GetString("IgnoreReportedReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat.
        /// </summary>
        public static string Inbox {
            get {
                return ResourceManager.GetString("Inbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructievideo&apos;s.
        /// </summary>
        public static string InstructionVideos {
            get {
                return ResourceManager.GetString("InstructionVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitnodigingen.
        /// </summary>
        public static string Invitations {
            get {
                return ResourceManager.GetString("Invitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitnodigen.
        /// </summary>
        public static string Invite {
            get {
                return ResourceManager.GetString("Invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buddy uitnodigen.
        /// </summary>
        public static string InviteBuddy {
            get {
                return ResourceManager.GetString("InviteBuddy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personen uitnodigen.
        /// </summary>
        public static string InviteUsers {
            get {
                return ResourceManager.GetString("InviteUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze kring verlaten.
        /// </summary>
        public static string LeaveCircle {
            get {
                return ResourceManager.GetString("LeaveCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inloggen.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitloggen.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to V&amp;A.
        /// </summary>
        public static string Marketplace {
            get {
                return ResourceManager.GetString("Marketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle advertenties.
        /// </summary>
        public static string MarketplaceAll {
            get {
                return ResourceManager.GetString("MarketplaceAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gevraagd.
        /// </summary>
        public static string MarketplaceAsked {
            get {
                return ResourceManager.GetString("MarketplaceAsked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto&apos;s.
        /// </summary>
        public static string MarketplaceCards {
            get {
                return ResourceManager.GetString("MarketplaceCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaats zelf een advertentie.
        /// </summary>
        public static string MarketplaceCreateAdd {
            get {
                return ResourceManager.GetString("MarketplaceCreateAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaats nu de eerste advertentie!.
        /// </summary>
        public static string MarketplaceCreateAddFirst {
            get {
                return ResourceManager.GetString("MarketplaceCreateAddFirst", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lijst.
        /// </summary>
        public static string MarketplaceListView {
            get {
                return ResourceManager.GetString("MarketplaceListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aangeboden.
        /// </summary>
        public static string MarketplaceOffered {
            get {
                return ResourceManager.GetString("MarketplaceOffered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertentie publiceren.
        /// </summary>
        public static string MarketplacePublish {
            get {
                return ResourceManager.GetString("MarketplacePublish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekijk alles.
        /// </summary>
        public static string MarketplaceShowAll {
            get {
                return ResourceManager.GetString("MarketplaceShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon meer advertenties.
        /// </summary>
        public static string MarketplaceShowMore {
            get {
                return ResourceManager.GetString("MarketplaceShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maaltijden.
        /// </summary>
        public static string Meals {
            get {
                return ResourceManager.GetString("Meals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leden.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berichten.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meer info.
        /// </summary>
        public static string MoreInfo {
            get {
                return ResourceManager.GetString("MoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meer informatie.
        /// </summary>
        public static string MoreInformation {
            get {
                return ResourceManager.GetString("MoreInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn buurtagenda.
        /// </summary>
        public static string MyActivities {
            get {
                return ResourceManager.GetString("MyActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn kringen.
        /// </summary>
        public static string MyCircles {
            get {
                return ResourceManager.GetString("MyCircles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn taken.
        /// </summary>
        public static string MyJobs {
            get {
                return ResourceManager.GetString("MyJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn vraag en aanbod.
        /// </summary>
        public static string MyMarketplace {
            get {
                return ResourceManager.GetString("MyMarketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn vraag en aanbod.
        /// </summary>
        public static string MyMarketplaceItems {
            get {
                return ResourceManager.GetString("MyMarketplaceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn buurtberichten.
        /// </summary>
        public static string MyMessages {
            get {
                return ResourceManager.GetString("MyMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn buurtplein.
        /// </summary>
        public static string MySquare {
            get {
                return ResourceManager.GetString("MySquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn buurtpleinen.
        /// </summary>
        public static string MySquares {
            get {
                return ResourceManager.GetString("MySquares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buurtagenda.
        /// </summary>
        public static string NeighborhoodActivities {
            get {
                return ResourceManager.GetString("NeighborhoodActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buurtnieuws.
        /// </summary>
        public static string NeighborhoodMessages {
            get {
                return ResourceManager.GetString("NeighborhoodMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buurtgenoten.
        /// </summary>
        public static string NeighborMessages {
            get {
                return ResourceManager.GetString("NeighborMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burenhulp.
        /// </summary>
        public static string NeighbourHelp {
            get {
                return ResourceManager.GetString("NeighbourHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe bijdrage plaatsen.
        /// </summary>
        public static string NewContribution {
            get {
                return ResourceManager.GetString("NewContribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw gesprek.
        /// </summary>
        public static string NewConversation {
            get {
                return ResourceManager.GetString("NewConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw bericht.
        /// </summary>
        public static string NewMessage {
            get {
                return ResourceManager.GetString("NewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volgende.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ga verder.
        /// </summary>
        public static string NextStep {
            get {
                return ResourceManager.GetString("NextStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik ga niet meer.
        /// </summary>
        public static string NotAttendingActivity {
            get {
                return ResourceManager.GetString("NotAttendingActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string OrganizationActivities {
            get {
                return ResourceManager.GetString("OrganizationActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buurtagenda feed.
        /// </summary>
        public static string OrganizationActivityFeed {
            get {
                return ResourceManager.GetString("OrganizationActivityFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voeg een product toe.
        /// </summary>
        public static string OrganizationAddProduct {
            get {
                return ResourceManager.GetString("OrganizationAddProduct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voeg een dienst toe.
        /// </summary>
        public static string OrganizationAddService {
            get {
                return ResourceManager.GetString("OrganizationAddService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medewerkers.
        /// </summary>
        public static string OrganizationMembers {
            get {
                return ResourceManager.GetString("OrganizationMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisaties.
        /// </summary>
        public static string OrganizationMessages {
            get {
                return ResourceManager.GetString("OrganizationMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buurtberichten feed.
        /// </summary>
        public static string OrganizationMessagesFeed {
            get {
                return ResourceManager.GetString("OrganizationMessagesFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisaties.
        /// </summary>
        public static string Organizations {
            get {
                return ResourceManager.GetString("Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle organisaties.
        /// </summary>
        public static string OrganizationsAll {
            get {
                return ResourceManager.GetString("OrganizationsAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verenigingen.
        /// </summary>
        public static string OrganizationsAssociation {
            get {
                return ResourceManager.GetString("OrganizationsAssociation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professionals.
        /// </summary>
        public static string OrganizationsProfessional {
            get {
                return ResourceManager.GetString("OrganizationsProfessional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijwilligers.
        /// </summary>
        public static string OrganizationsVolunteer {
            get {
                return ResourceManager.GetString("OrganizationsVolunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overzicht.
        /// </summary>
        public static string Overview {
            get {
                return ResourceManager.GetString("Overview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openstaande verzoeken.
        /// </summary>
        public static string PendingJoinRequests {
            get {
                return ResourceManager.GetString("PendingJoinRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto&apos;s.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bericht vastzetten.
        /// </summary>
        public static string PinConfirmation {
            get {
                return ResourceManager.GetString("PinConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bericht vastzetten.
        /// </summary>
        public static string PinListItemText {
            get {
                return ResourceManager.GetString("PinListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaats bericht.
        /// </summary>
        public static string PostMessage {
            get {
                return ResourceManager.GetString("PostMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaats reactie.
        /// </summary>
        public static string PostReaction {
            get {
                return ResourceManager.GetString("PostReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorige.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openbare kringen.
        /// </summary>
        public static string PublicCircles {
            get {
                return ResourceManager.GetString("PublicCircles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reageer.
        /// </summary>
        public static string React {
            get {
                return ResourceManager.GetString("React", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lees verder.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu echt afronden.
        /// </summary>
        public static string RealFinish {
            get {
                return ResourceManager.GetString("RealFinish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontvangen.
        /// </summary>
        public static string Received {
            get {
                return ResourceManager.GetString("Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiel aanmaken.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak een nieuw profiel aan.
        /// </summary>
        public static string RegisterAsNewUser {
            get {
                return ResourceManager.GetString("RegisterAsNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afwijzen.
        /// </summary>
        public static string Reject {
            get {
                return ResourceManager.GetString("Reject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijderen.
        /// </summary>
        public static string Remove {
            get {
                return ResourceManager.GetString("Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiel verwijderen.
        /// </summary>
        public static string RemoveAccount {
            get {
                return ResourceManager.GetString("RemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze activiteit verwijderen.
        /// </summary>
        public static string RemoveActivity {
            get {
                return ResourceManager.GetString("RemoveActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze beheerder verwijderen.
        /// </summary>
        public static string RemoveAdmin {
            get {
                return ResourceManager.GetString("RemoveAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze kring verwijderen.
        /// </summary>
        public static string RemoveCircle {
            get {
                return ResourceManager.GetString("RemoveCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijder document.
        /// </summary>
        public static string RemoveDocument {
            get {
                return ResourceManager.GetString("RemoveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit gesprek verlaten.
        /// </summary>
        public static string RemoveEmailGroup {
            get {
                return ResourceManager.GetString("RemoveEmailGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit feit verwijderen.
        /// </summary>
        public static string RemoveFact {
            get {
                return ResourceManager.GetString("RemoveFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze taak verwijderen.
        /// </summary>
        public static string RemoveJob {
            get {
                return ResourceManager.GetString("RemoveJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze advertentie verwijderen.
        /// </summary>
        public static string RemoveMarketplaceItem {
            get {
                return ResourceManager.GetString("RemoveMarketplaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit lid verwijderen.
        /// </summary>
        public static string RemoveMember {
            get {
                return ResourceManager.GetString("RemoveMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beheerrechten intrekken.
        /// </summary>
        public static string RemoveMemberAdminRights {
            get {
                return ResourceManager.GetString("RemoveMemberAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit nieuwsbericht verwijderen.
        /// </summary>
        public static string RemoveNeighborhoodMessage {
            get {
                return ResourceManager.GetString("RemoveNeighborhoodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze reactie verwijderen.
        /// </summary>
        public static string RemoveNeighborhoodMessageReaction {
            get {
                return ResourceManager.GetString("RemoveNeighborhoodMessageReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze medewerker verwijderen.
        /// </summary>
        public static string RemoveOrganizationMember {
            get {
                return ResourceManager.GetString("RemoveOrganizationMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijder deze foto..
        /// </summary>
        public static string RemovePhoto {
            get {
                return ResourceManager.GetString("RemovePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijder fotoalbum.
        /// </summary>
        public static string RemovePhotoAlbum {
            get {
                return ResourceManager.GetString("RemovePhotoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beantwoorden.
        /// </summary>
        public static string Reply {
            get {
                return ResourceManager.GetString("Reply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allen beantwoorden.
        /// </summary>
        public static string ReplyAll {
            get {
                return ResourceManager.GetString("ReplyAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misbruik melden.
        /// </summary>
        public static string ReportAbuse {
            get {
                return ResourceManager.GetString("ReportAbuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerapporteerde reacties.
        /// </summary>
        public static string ReportedReactions {
            get {
                return ResourceManager.GetString("ReportedReactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanvragen.
        /// </summary>
        public static string Request {
            get {
                return ResourceManager.GetString("Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe organisatie aanvragen.
        /// </summary>
        public static string RequestNewOrganization {
            get {
                return ResourceManager.GetString("RequestNewOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzoek verstuurd.
        /// </summary>
        public static string RequestSent {
            get {
                return ResourceManager.GetString("RequestSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechtsom draaien.
        /// </summary>
        public static string RotateRight {
            get {
                return ResourceManager.GetString("RotateRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opslaan en nieuwe taak maken.
        /// </summary>
        public static string SaveAndCreateTask {
            get {
                return ResourceManager.GetString("SaveAndCreateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiel opslaan.
        /// </summary>
        public static string SaveProfile {
            get {
                return ResourceManager.GetString("SaveProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer.
        /// </summary>
        public static string Select {
            get {
                return ResourceManager.GetString("Select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indienen.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verstuur instructies.
        /// </summary>
        public static string SendInstructions {
            get {
                return ResourceManager.GetString("SendInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verstuur bericht.
        /// </summary>
        public static string SendMessage {
            get {
                return ResourceManager.GetString("SendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuur bericht naar adverteerder.
        /// </summary>
        public static string SendMessageToMarketplaceItemOwner {
            get {
                return ResourceManager.GetString("SendMessageToMarketplaceItemOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuur ons een e-mail.
        /// </summary>
        public static string SendUsAnEmail {
            get {
                return ResourceManager.GetString("SendUsAnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activeer.
        /// </summary>
        public static string SetActive {
            get {
                return ResourceManager.GetString("SetActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak deze kring privé.
        /// </summary>
        public static string SetCirclePrivate {
            get {
                return ResourceManager.GetString("SetCirclePrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak deze kring openbaar.
        /// </summary>
        public static string SetCirclePublic {
            get {
                return ResourceManager.GetString("SetCirclePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle notificaties weergeven.
        /// </summary>
        public static string ShowAllNotifications {
            get {
                return ResourceManager.GetString("ShowAllNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontvang notificaties.
        /// </summary>
        public static string StartCircleEmails {
            get {
                return ResourceManager.GetString("StartCircleEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startpagina.
        /// </summary>
        public static string StartPage {
            get {
                return ResourceManager.GetString("StartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop notificaties.
        /// </summary>
        public static string StopCircleEmails {
            get {
                return ResourceManager.GetString("StopCircleEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spullen te koop.
        /// </summary>
        public static string StuffForSale {
            get {
                return ResourceManager.GetString("StuffForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spullen te leen.
        /// </summary>
        public static string StuffToBorrow {
            get {
                return ResourceManager.GetString("StuffToBorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuiderlingen overmaken.
        /// </summary>
        public static string TransferZuiderlings {
            get {
                return ResourceManager.GetString("TransferZuiderlings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik kan niet meer!.
        /// </summary>
        public static string UnassignJobToMe {
            get {
                return ResourceManager.GetString("UnassignJobToMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bericht losmaken.
        /// </summary>
        public static string UnpinConfirmation {
            get {
                return ResourceManager.GetString("UnpinConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bericht losmaken.
        /// </summary>
        public static string UnpinListItemText {
            get {
                return ResourceManager.GetString("UnpinListItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nu stemmen.
        /// </summary>
        public static string VoteAction {
            get {
                return ResourceManager.GetString("VoteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzonden.
        /// </summary>
        public static string WasSend {
            get {
                return ResourceManager.GetString("WasSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ja, die heb ik!.
        /// </summary>
        public static string YesIHave {
            get {
                return ResourceManager.GetString("YesIHave", resourceCulture);
            }
        }
    }
}
