//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeeftSamen.Common.InterfaceText {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Error {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Error() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeeftSamen.Common.InterfaceText.Error", typeof(Error).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je moet akkoord gaan met onze voorwaarden.
        /// </summary>
        public static string AcceptTermsIsRequired {
            get {
                return ResourceManager.GetString("AcceptTermsIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit account is niet meer actief..
        /// </summary>
        public static string AccountDoesntExist {
            get {
                return ResourceManager.GetString("AccountDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De einddatum kan niet eerder zijn dan de aanvangsdatum..
        /// </summary>
        public static string ActivityEndDateBeforeStartDate {
            get {
                return ResourceManager.GetString("ActivityEndDateBeforeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een einddatum is nodig..
        /// </summary>
        public static string ActivityEndDateIsRequired {
            get {
                return ResourceManager.GetString("ActivityEndDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een begindatum is nodig..
        /// </summary>
        public static string ActivityStartDateIsRequired {
            get {
                return ResourceManager.GetString("ActivityStartDateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een adres is nodig..
        /// </summary>
        public static string AddressIsRequired {
            get {
                return ResourceManager.GetString("AddressIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het ingevoerde adres werd niet gevonden. Heb je de juiste postcode en het juiste huisnummer ingevoerd? Probeer het opnieuw of gebruik handmatige invoer..
        /// </summary>
        public static string AddressNotFound {
            get {
                return ResourceManager.GetString("AddressNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een categorie is nodig..
        /// </summary>
        public static string CategoryIsRequired {
            get {
                return ResourceManager.GetString("CategoryIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze kring bestaat (niet) meer..
        /// </summary>
        public static string CircleDoesntExist {
            get {
                return ResourceManager.GetString("CircleDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een plaatsnaam is nodig..
        /// </summary>
        public static string CityIsRequired {
            get {
                return ResourceManager.GetString("CityIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De einddatum is vereist als u de taak wilt herhalen.
        /// </summary>
        public static string CompletionDateTimeIsRequired {
            get {
                return ResourceManager.GetString("CompletionDateTimeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je moet je wachtwoord bevestigen..
        /// </summary>
        public static string ConfirmPasswordIsRequired {
            get {
                return ResourceManager.GetString("ConfirmPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een bevestiging is nodig..
        /// </summary>
        public static string ConfirmRemoveAccount {
            get {
                return ResourceManager.GetString("ConfirmRemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het huidige wachtwoord is nodig..
        /// </summary>
        public static string CurrentPasswordIsRequired {
            get {
                return ResourceManager.GetString("CurrentPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een datum is nodig..
        /// </summary>
        public static string DateIsRequired {
            get {
                return ResourceManager.GetString("DateIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een omschrijving is nodig..
        /// </summary>
        public static string DescriptionIsRequired {
            get {
                return ResourceManager.GetString("DescriptionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het e-mailadres is niet geldig.
        /// </summary>
        public static string EmailAddressIsInvalid {
            get {
                return ResourceManager.GetString("EmailAddressIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een geldig e-mailadres is nodig..
        /// </summary>
        public static string EmailAddressIsRequired {
            get {
                return ResourceManager.GetString("EmailAddressIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit e-mailadres wordt al door iemand gebruikt..
        /// </summary>
        public static string EmailAddressTaken {
            get {
                return ResourceManager.GetString("EmailAddressTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een huisnummer is nodig..
        /// </summary>
        public static string HouseNumberIsRequired {
            get {
                return ResourceManager.GetString("HouseNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een intructie is nodig..
        /// </summary>
        public static string IntroductionIsRequired {
            get {
                return ResourceManager.GetString("IntroductionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De introductie mag maximaal 140 tekens lang zijn..
        /// </summary>
        public static string IntroductionMaxLength {
            get {
                return ResourceManager.GetString("IntroductionMaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt waarschijnlijk een foutje gemaakt bij het invullen van je gegevens. Probeer het opnieuw..
        /// </summary>
        public static string InvalidLogin {
            get {
                return ResourceManager.GetString("InvalidLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitnodiging bestaat (niet) meer of is ingetrokken..
        /// </summary>
        public static string InvitationDoesntExist {
            get {
                return ResourceManager.GetString("InvitationDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je activeer code is te oud, je had maximaal 10 dagen om te reageren..
        /// </summary>
        public static string InvitationExpired {
            get {
                return ResourceManager.GetString("InvitationExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De uitnodiging is niet voor het account waarmee je ingelogd was. Meld je aan met het e-mail adres waar de uitnodiging naar verzonden was..
        /// </summary>
        public static string InvitationWrongUser {
            get {
                return ResourceManager.GetString("InvitationWrongUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is al iemand anders ingelogd op LeeftSamen. Log in met je eigen profiel om je bericht te bekijken..
        /// </summary>
        public static string InvitationWrongUserAccepted {
            get {
                return ResourceManager.GetString("InvitationWrongUserAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De einddatum kan niet eerder zijn dan de aanvangsdatum..
        /// </summary>
        public static string JobEndDateBeforeStartDate {
            get {
                return ResourceManager.GetString("JobEndDateBeforeStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een locatie is nodig..
        /// </summary>
        public static string LocationIsRequired {
            get {
                return ResourceManager.GetString("LocationIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een logo is nodig..
        /// </summary>
        public static string LogoIsRequired {
            get {
                return ResourceManager.GetString("LogoIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een type is nodig..
        /// </summary>
        public static string MarketplaceItemTypeRequired {
            get {
                return ResourceManager.GetString("MarketplaceItemTypeRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De {0} mag maximaal {1} karakters lang zijn..
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De tekst in het bericht is nodig..
        /// </summary>
        public static string MessageTextRequired {
            get {
                return ResourceManager.GetString("MessageTextRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De {0} moet minimaal {1} karakters lang zijn..
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een kringnaam is nodig..
        /// </summary>
        public static string NameOfCircleIsRequired {
            get {
                return ResourceManager.GetString("NameOfCircleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een groepsnaam is nodig..
        /// </summary>
        public static string NameOfGroupIsRequired {
            get {
                return ResourceManager.GetString("NameOfGroupIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een naam voor het buurtplein is verplicht.
        /// </summary>
        public static string NameOfSquareIsRequired {
            get {
                return ResourceManager.GetString("NameOfSquareIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een nieuw wachtwoord is nodig..
        /// </summary>
        public static string NewPasswordIsRequired {
            get {
                return ResourceManager.GetString("NewPasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De nieuwe wachtwoorden komen niet overeen..
        /// </summary>
        public static string NewPasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("NewPasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul een getal in..
        /// </summary>
        public static string NumericRequired {
            get {
                return ResourceManager.GetString("NumericRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een organisatienaam is nodig..
        /// </summary>
        public static string OrganizationNameIsRequired {
            get {
                return ResourceManager.GetString("OrganizationNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een organisatietype is nodig..
        /// </summary>
        public static string OrganizationTypeIsRequired {
            get {
                return ResourceManager.GetString("OrganizationTypeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een wachtwoord is nodig..
        /// </summary>
        public static string PasswordIsRequired {
            get {
                return ResourceManager.GetString("PasswordIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het wachtwoord moet tenminste {2} tekens lang zijn..
        /// </summary>
        public static string PasswordLength {
            get {
                return ResourceManager.GetString("PasswordLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De ingevoerde wachtwoorden komen niet overeen..
        /// </summary>
        public static string PasswordsDoNotMatch {
            get {
                return ResourceManager.GetString("PasswordsDoNotMatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het wachtwoord moet tenminste 8 tekens lang zijn en 1 hoofdletter en 1 cijfer bevatten..
        /// </summary>
        public static string PasswordStrength {
            get {
                return ResourceManager.GetString("PasswordStrength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een telefoonnummer is nodig..
        /// </summary>
        public static string PhoneNumberIsRequired {
            get {
                return ResourceManager.GetString("PhoneNumberIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een postcode is nodig..
        /// </summary>
        public static string PostalCodeIsRequired {
            get {
                return ResourceManager.GetString("PostalCodeIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een profielfoto is nodig..
        /// </summary>
        public static string ProfileImageIsRequired {
            get {
                return ResourceManager.GetString("ProfileImageIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De {0} moet een positief getal zijn..
        /// </summary>
        public static string RangeNumericPositive {
            get {
                return ResourceManager.GetString("RangeNumericPositive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een reactie is nodig..
        /// </summary>
        public static string ReactionIsRequired {
            get {
                return ResourceManager.GetString("ReactionIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt niemand uitgekozen om het bericht naar te versturen..
        /// </summary>
        public static string RecipientIsRequired {
            get {
                return ResourceManager.GetString("RecipientIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer minimaal één wijk..
        /// </summary>
        public static string SelectOneNeighborhood {
            get {
                return ResourceManager.GetString("SelectOneNeighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer minimaal één thema..
        /// </summary>
        public static string SelectOneTheme {
            get {
                return ResourceManager.GetString("SelectOneTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een onderwerp is nodig..
        /// </summary>
        public static string SubjectRequired {
            get {
                return ResourceManager.GetString("SubjectRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een titel is nodig..
        /// </summary>
        public static string TitleIsRequired {
            get {
                return ResourceManager.GetString("TitleIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een gemeente is nodig..
        /// </summary>
        public static string TownIsRequired {
            get {
                return ResourceManager.GetString("TownIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bent al lid van deze kring..
        /// </summary>
        public static string UserAlreadyMemberOfCircle {
            get {
                return ResourceManager.GetString("UserAlreadyMemberOfCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De website-URL moet beginnen met http:// of https://.
        /// </summary>
        public static string WebsiteFormat {
            get {
                return ResourceManager.GetString("WebsiteFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een website is nodig..
        /// </summary>
        public static string WebsiteIsRequired {
            get {
                return ResourceManager.GetString("WebsiteIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vink de dagen aan waarop de taak herhaald moet worden..
        /// </summary>
        public static string WeekdayIsRequired {
            get {
                return ResourceManager.GetString("WeekdayIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef een geboortedatum op..
        /// </summary>
        public static string YourDateOfBirthIsRequired {
            get {
                return ResourceManager.GetString("YourDateOfBirthIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geslacht is een verplicht veld..
        /// </summary>
        public static string YourGenderIsRequired {
            get {
                return ResourceManager.GetString("YourGenderIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je naam is nodig..
        /// </summary>
        public static string YourNameIsRequired {
            get {
                return ResourceManager.GetString("YourNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je e-mailadres is nodig..
        /// </summary>
        public static string YourUsernameIsRequired {
            get {
                return ResourceManager.GetString("YourUsernameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account geblokkeerd..
        /// </summary>
        public static string ZuiderlingAccountBlocked {
            get {
                return ResourceManager.GetString("ZuiderlingAccountBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je account kan op dit moment niet geverifieerd worden..
        /// </summary>
        public static string ZuiderlingAccountException {
            get {
                return ResourceManager.GetString("ZuiderlingAccountException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een account is nodig..
        /// </summary>
        public static string ZuiderlingAccountIsRequired {
            get {
                return ResourceManager.GetString("ZuiderlingAccountIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingevulde accountgegevens onjuist..
        /// </summary>
        public static string ZuiderlingAccountWrong {
            get {
                return ResourceManager.GetString("ZuiderlingAccountWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een wachtwoord is nodig..
        /// </summary>
        public static string ZuiderlingPasswordIsRequired {
            get {
                return ResourceManager.GetString("ZuiderlingPasswordIsRequired", resourceCulture);
            }
        }
    }
}
