//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeeftSamen.Common.InterfaceText {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Label {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Label() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeeftSamen.Common.InterfaceText.Label", typeof(Label).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik ga akkoord met de algemene voorwaarden.
        /// </summary>
        public static string AcceptTerms {
            get {
                return ResourceManager.GetString("AcceptTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik ga akkoord met de &lt;a onclick=&quot;_paq.push([&apos;trackEvent&apos;, &apos;Footer&apos;, &apos;TermsAndConditions&apos;]);&quot; href=&quot;/page/termsandconditions&quot;&gt;algemene voorwaarden&lt;/a&gt;.
        /// </summary>
        public static string AcceptTermsHref {
            get {
                return ResourceManager.GetString("AcceptTermsHref", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voorwaarden.
        /// </summary>
        public static string AcceptTermsName {
            get {
                return ResourceManager.GetString("AcceptTermsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actief afgelopen 24 uur.
        /// </summary>
        public static string ActiveLast24Hours {
            get {
                return ResourceManager.GetString("ActiveLast24Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actief afgelopen 7 dagen.
        /// </summary>
        public static string ActiveLast7Days {
            get {
                return ResourceManager.GetString("ActiveLast7Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actief afgelopen uur.
        /// </summary>
        public static string ActiveLastHour {
            get {
                return ResourceManager.GetString("ActiveLastHour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteiten.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tot.
        /// </summary>
        public static string ActivityEnd {
            get {
                return ResourceManager.GetString("ActivityEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Einddatum.
        /// </summary>
        public static string ActivityEndDate {
            get {
                return ResourceManager.GetString("ActivityEndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanvang.
        /// </summary>
        public static string ActivityStart {
            get {
                return ResourceManager.GetString("ActivityStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanvangsdatum.
        /// </summary>
        public static string ActivityStartDate {
            get {
                return ResourceManager.GetString("ActivityStartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adres.
        /// </summary>
        public static string Address {
            get {
                return ResourceManager.GetString("Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beheerder.
        /// </summary>
        public static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeftijd.
        /// </summary>
        public static string Age {
            get {
                return ResourceManager.GetString("Age", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeftijd vanaf.
        /// </summary>
        public static string AgeFrom {
            get {
                return ResourceManager.GetString("AgeFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leeftijd tot en met.
        /// </summary>
        public static string AgeTo {
            get {
                return ResourceManager.GetString("AgeTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle leeftijden.
        /// </summary>
        public static string AllAges {
            get {
                return ResourceManager.GetString("AllAges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze activiteit is geschikt voor alle leeftijden.
        /// </summary>
        public static string AllAgesActivity {
            get {
                return ResourceManager.GetString("AllAgesActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle categorieën.
        /// </summary>
        public static string AllCategories {
            get {
                return ResourceManager.GetString("AllCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle kringleden.
        /// </summary>
        public static string AllCircleMembers {
            get {
                return ResourceManager.GetString("AllCircleMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze activiteit duurt de hele dag.
        /// </summary>
        public static string AllDayActivity {
            get {
                return ResourceManager.GetString("AllDayActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gevraagd.
        /// </summary>
        public static string Asked {
            get {
                return ResourceManager.GetString("Asked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vereniging.
        /// </summary>
        public static string Association {
            get {
                return ResourceManager.GetString("Association", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachment.
        /// </summary>
        public static string Attachment {
            get {
                return ResourceManager.GetString("Attachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemiddeld aantal deelnemers.
        /// </summary>
        public static string AverageActivityAttendees {
            get {
                return ResourceManager.GetString("AverageActivityAttendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemiddelde buurtstraal.
        /// </summary>
        public static string AverageNeighborhoodRadius {
            get {
                return ResourceManager.GetString("AverageNeighborhoodRadius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beiden.
        /// </summary>
        public static string Both {
            get {
                return ResourceManager.GetString("Both", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door.
        /// </summary>
        public static string By {
            get {
                return ResourceManager.GetString("By", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig bericht.
        /// </summary>
        public static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail instellingen.
        /// </summary>
        public static string ChangeEmailSettings {
            get {
                return ResourceManager.GetString("ChangeEmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificatie instellingen.
        /// </summary>
        public static string ChangeNotifications {
            get {
                return ResourceManager.GetString("ChangeNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuiderling koppelen.
        /// </summary>
        public static string ChangeZuiderling {
            get {
                return ResourceManager.GetString("ChangeZuiderling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies een categorie.
        /// </summary>
        public static string ChooseCategory {
            get {
                return ResourceManager.GetString("ChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies een logo.
        /// </summary>
        public static string ChooseLogo {
            get {
                return ResourceManager.GetString("ChooseLogo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kringbeheerder.
        /// </summary>
        public static string CircleAdministrator {
            get {
                return ResourceManager.GetString("CircleAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kringlid.
        /// </summary>
        public static string CircleMember {
            get {
                return ResourceManager.GetString("CircleMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schrijf hier iets over jezelf. Wie ben je? Wat doe je? Wat vind je leuk?.
        /// </summary>
        public static string CircleProfile {
            get {
                return ResourceManager.GetString("CircleProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaatsnaam.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opgehaald.
        /// </summary>
        public static string Collected {
            get {
                return ResourceManager.GetString("Collected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herhaal de taak tot.
        /// </summary>
        public static string CompletionDateTime {
            get {
                return ResourceManager.GetString("CompletionDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevestig je nieuwe wachtwoord..
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevestig je wachtwoord..
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevestig dat je je profiel wilt verwijderen..
        /// </summary>
        public static string ConfirmRemoveAccount {
            get {
                return ResourceManager.GetString("ConfirmRemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heb je geen sfeerfoto? Kies een kleur.
        /// </summary>
        public static string CoverColor {
            get {
                return ResourceManager.GetString("CoverColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sfeerfoto.
        /// </summary>
        public static string CoverImage {
            get {
                return ResourceManager.GetString("CoverImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huidig wachtwoord.
        /// </summary>
        public static string CurrentPassword {
            get {
                return ResourceManager.GetString("CurrentPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huidige profielfoto.
        /// </summary>
        public static string CurrentProfileImage {
            get {
                return ResourceManager.GetString("CurrentProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum.
        /// </summary>
        public static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geboortedatum.
        /// </summary>
        public static string DateOfBirth {
            get {
                return ResourceManager.GetString("DateOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum en tijd.
        /// </summary>
        public static string DateTime {
            get {
                return ResourceManager.GetString("DateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dag.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dag geleden.
        /// </summary>
        public static string DayAgo {
            get {
                return ResourceManager.GetString("DayAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} dagen geleden.
        /// </summary>
        public static string DaysAgo {
            get {
                return ResourceManager.GetString("DaysAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *.
        /// </summary>
        public static string DefaultRequiredSuffix {
            get {
                return ResourceManager.GetString("DefaultRequiredSuffix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijder bericht.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijderd.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omschrijving.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon als.
        /// </summary>
        public static string DisplayAs {
            get {
                return ResourceManager.GetString("DisplayAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nee, bedankt.
        /// </summary>
        public static string DontMakeMePioneer {
            get {
                return ResourceManager.GetString("DontMakeMePioneer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wanneer de taak van start gaat.
        /// </summary>
        public static string DueDateTime {
            get {
                return ResourceManager.GetString("DueDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon eerdere berichten.
        /// </summary>
        public static string EarlierEmails {
            get {
                return ResourceManager.GetString("EarlierEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon eerdere reacties.
        /// </summary>
        public static string EarlierReactions {
            get {
                return ResourceManager.GetString("EarlierReactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadres.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadressen.
        /// </summary>
        public static string Emails {
            get {
                return ResourceManager.GetString("Emails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eindtijd.
        /// </summary>
        public static string EndTime {
            get {
                return ResourceManager.GetString("EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verloopdatum.
        /// </summary>
        public static string ExpirationDate {
            get {
                return ResourceManager.GetString("ExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verloopdatum.
        /// </summary>
        public static string ExpirationDateTime {
            get {
                return ResourceManager.GetString("ExpirationDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrouw.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestanden.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forum.
        /// </summary>
        public static string Forum {
            get {
                return ResourceManager.GetString("Forum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijdag.
        /// </summary>
        public static string Friday {
            get {
                return ResourceManager.GetString("Friday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Van.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vanaf.
        /// </summary>
        public static string FromAge {
            get {
                return ResourceManager.GetString("FromAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volledige tekst.
        /// </summary>
        public static string FullText {
            get {
                return ResourceManager.GetString("FullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geslacht.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algemeen.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onderwerp gesprek.
        /// </summary>
        public static string GroupName {
            get {
                return ResourceManager.GetString("GroupName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijd maakt niet uit.
        /// </summary>
        public static string HasNoDueDate {
            get {
                return ResourceManager.GetString("HasNoDueDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} uur geleden.
        /// </summary>
        public static string HourAgo {
            get {
                return ResourceManager.GetString("HourAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} uren geleden.
        /// </summary>
        public static string HoursAgo {
            get {
                return ResourceManager.GetString("HoursAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Huisnummer.
        /// </summary>
        public static string HouseNumber {
            get {
                return ResourceManager.GetString("HouseNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik ben op zoek naar (een).
        /// </summary>
        public static string IAmSearchingfor {
            get {
                return ResourceManager.GetString("IAmSearchingfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afbeelding.
        /// </summary>
        public static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afbeeldingen.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        public static string In {
            get {
                return ResourceManager.GetString("In", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructievideo&apos;s.
        /// </summary>
        public static string InstructionVideos {
            get {
                return ResourceManager.GetString("InstructionVideos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introductiefoto.
        /// </summary>
        public static string IntroductionImage {
            get {
                return ResourceManager.GetString("IntroductionImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introductietekst.
        /// </summary>
        public static string IntroductionText {
            get {
                return ResourceManager.GetString("IntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introductietekst (max. 250 tekens).
        /// </summary>
        public static string IntroductionTextNeighborhoodMessage {
            get {
                return ResourceManager.GetString("IntroductionTextNeighborhoodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitnodiging verlopen.
        /// </summary>
        public static string InvitationExpired {
            get {
                return ResourceManager.GetString("InvitationExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitgenodigd voor kring.
        /// </summary>
        public static string InvitedToCircle {
            get {
                return ResourceManager.GetString("InvitedToCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitgenodigd voor organisatie.
        /// </summary>
        public static string InvitedToOrganization {
            get {
                return ResourceManager.GetString("InvitedToOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensen uitnodigen via e-mail.
        /// </summary>
        public static string InviteUsersByEmail {
            get {
                return ResourceManager.GetString("InviteUsersByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik heb hulp nodig met (een).
        /// </summary>
        public static string IRequireHelpWith {
            get {
                return ResourceManager.GetString("IRequireHelpWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openbaar.
        /// </summary>
        public static string IsPublic {
            get {
                return ResourceManager.GetString("IsPublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je kunt maximaal 4000 karakters gebruiken in je omschrijving. Resterend: .
        /// </summary>
        public static string JobCreateDescriptionInfo {
            get {
                return ResourceManager.GetString("JobCreateDescriptionInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wie mogen de taak zien?.
        /// </summary>
        public static string JobVisibility {
            get {
                return ResourceManager.GetString("JobVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laatst bewerkt.
        /// </summary>
        public static string LastEdited {
            get {
                return ResourceManager.GetString("LastEdited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laatste bericht.
        /// </summary>
        public static string LastMessage {
            get {
                return ResourceManager.GetString("LastMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon minder berichten.
        /// </summary>
        public static string LessEmails {
            get {
                return ResourceManager.GetString("LessEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon minder reacties.
        /// </summary>
        public static string LessReactions {
            get {
                return ResourceManager.GetString("LessReactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lijst.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locatie.
        /// </summary>
        public static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logo.
        /// </summary>
        public static string Logo {
            get {
                return ResourceManager.GetString("Logo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitgebreide omschrijving.
        /// </summary>
        public static string LongDescription {
            get {
                return ResourceManager.GetString("LongDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afbeelding 1 &lt;small&gt;Hoofdafbeelding&lt;/small&gt;.
        /// </summary>
        public static string MainImage {
            get {
                return ResourceManager.GetString("MainImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik wil graag pionier voor LeeftSamen worden..
        /// </summary>
        public static string MakeMePioneer {
            get {
                return ResourceManager.GetString("MakeMePioneer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Man.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leden.
        /// </summary>
        public static string Members {
            get {
                return ResourceManager.GetString("Members", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bericht.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit bericht heeft een vervaldatum..
        /// </summary>
        public static string MessageExpires {
            get {
                return ResourceManager.GetString("MessageExpires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RE: .
        /// </summary>
        public static string MessageReplied {
            get {
                return ResourceManager.GetString("MessageReplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berichten.
        /// </summary>
        public static string Messages {
            get {
                return ResourceManager.GetString("Messages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekst.
        /// </summary>
        public static string MessageText {
            get {
                return ResourceManager.GetString("MessageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meter.
        /// </summary>
        public static string Meter {
            get {
                return ResourceManager.GetString("Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} meter bij jou vandaan.
        /// </summary>
        public static string MeterAway {
            get {
                return ResourceManager.GetString("MeterAway", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minuut geleden.
        /// </summary>
        public static string MinuteAgo {
            get {
                return ResourceManager.GetString("MinuteAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} minuten geleden.
        /// </summary>
        public static string MinutesAgo {
            get {
                return ResourceManager.GetString("MinutesAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maandag.
        /// </summary>
        public static string Monday {
            get {
                return ResourceManager.GetString("Monday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maand.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} maand geleden.
        /// </summary>
        public static string MonthAgo {
            get {
                return ResourceManager.GetString("MonthAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} maanden geleden.
        /// </summary>
        public static string MonthsAgo {
            get {
                return ResourceManager.GetString("MonthsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meer reacties.
        /// </summary>
        public static string MoreReactions {
            get {
                return ResourceManager.GetString("MoreReactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tip: je kunt hier ook leuke filmpjes uploaden!.
        /// </summary>
        public static string MovieTip {
            get {
                return ResourceManager.GetString("MovieTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn profiel.
        /// </summary>
        public static string MyAccount {
            get {
                return ResourceManager.GetString("MyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn profielen.
        /// </summary>
        public static string MyAccounts {
            get {
                return ResourceManager.GetString("MyAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam:.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kringnaam:.
        /// </summary>
        public static string NameOfCircle {
            get {
                return ResourceManager.GetString("NameOfCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam buurtplein.
        /// </summary>
        public static string NameOfSquare {
            get {
                return ResourceManager.GetString("NameOfSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buurtinstellingen.
        /// </summary>
        public static string NeighborhoodSettings {
            get {
                return ResourceManager.GetString("NeighborhoodSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw wachtwoord.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe profielfoto.
        /// </summary>
        public static string NewProfileImage {
            get {
                return ResourceManager.GetString("NewProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voor deze dag zijn er geen taken..
        /// </summary>
        public static string NoJobsThisDay {
            get {
                return ResourceManager.GetString("NoJobsThisDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen.
        /// </summary>
        public static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn geen openbare kringen in je buurt gevonden..
        /// </summary>
        public static string NoPublicCirclesInNeighborhoodFound {
            get {
                return ResourceManager.GetString("NoPublicCirclesInNeighborhoodFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen resultaat.
        /// </summary>
        public static string NoResult {
            get {
                return ResourceManager.GetString("NoResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijd maakt niet uit.
        /// </summary>
        public static string NoStartTime {
            get {
                return ResourceManager.GetString("NoStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bent nog geen lid van een kring..
        /// </summary>
        public static string NoUserCircles {
            get {
                return ResourceManager.GetString("NoUserCircles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aangeboden.
        /// </summary>
        public static string Offered {
            get {
                return ResourceManager.GetString("Offered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemiddeld.
        /// </summary>
        public static string OnAverage {
            get {
                return ResourceManager.GetString("OnAverage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alleen geselecteerde kringleden.
        /// </summary>
        public static string OnlySelectedCircleMembers {
            get {
                return ResourceManager.GetString("OnlySelectedCircleMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openingstijden.
        /// </summary>
        public static string OpeningHours {
            get {
                return ResourceManager.GetString("OpeningHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op datum.
        /// </summary>
        public static string OrderByDate {
            get {
                return ResourceManager.GetString("OrderByDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op afstand.
        /// </summary>
        public static string OrderByDistance {
            get {
                return ResourceManager.GetString("OrderByDistance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op prijs (oplopend).
        /// </summary>
        public static string OrderByPrice {
            get {
                return ResourceManager.GetString("OrderByPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op prijs (aflopend).
        /// </summary>
        public static string OrderByPriceDesc {
            get {
                return ResourceManager.GetString("OrderByPriceDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisatiethema&apos;s.
        /// </summary>
        public static string OrganisationThemes {
            get {
                return ResourceManager.GetString("OrganisationThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omgeving waar de organisatie actief is.
        /// </summary>
        public static string OrganizationActiveInDistricts {
            get {
                return ResourceManager.GetString("OrganizationActiveInDistricts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medewerker.
        /// </summary>
        public static string OrganizationMember {
            get {
                return ResourceManager.GetString("OrganizationMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam van de organisatie.
        /// </summary>
        public static string OrganizationName {
            get {
                return ResourceManager.GetString("OrganizationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitgebreide omschijving.
        /// </summary>
        public static string OrganizationProductFullText {
            get {
                return ResourceManager.GetString("OrganizationProductFullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introductietekst.
        /// </summary>
        public static string OrganizationProductIntroductionText {
            get {
                return ResourceManager.GetString("OrganizationProductIntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam van je product.
        /// </summary>
        public static string OrganizationProductTitle {
            get {
                return ResourceManager.GetString("OrganizationProductTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitgebreide omschijving.
        /// </summary>
        public static string OrganizationServiceFullText {
            get {
                return ResourceManager.GetString("OrganizationServiceFullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introductietekst.
        /// </summary>
        public static string OrganizationServiceIntroductionText {
            get {
                return ResourceManager.GetString("OrganizationServiceIntroductionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam van je dienst.
        /// </summary>
        public static string OrganizationServiceTitle {
            get {
                return ResourceManager.GetString("OrganizationServiceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisatietype.
        /// </summary>
        public static string OrganizationType {
            get {
                return ResourceManager.GetString("OrganizationType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deelnemers.
        /// </summary>
        public static string Participants {
            get {
                return ResourceManager.GetString("Participants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Euro&apos;s.
        /// </summary>
        public static string PaymentCurrencyEuro {
            get {
                return ResourceManager.GetString("PaymentCurrencyEuro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuiderlingen.
        /// </summary>
        public static string PaymentCurrencyZuiderling {
            get {
                return ResourceManager.GetString("PaymentCurrencyZuiderling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doe een bod!.
        /// </summary>
        public static string PaymentOptionAuction {
            get {
                return ResourceManager.GetString("PaymentOptionAuction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gratis!.
        /// </summary>
        public static string PaymentOptionFree {
            get {
                return ResourceManager.GetString("PaymentOptionFree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaste prijs.
        /// </summary>
        public static string PaymentOptionPlaceholder {
            get {
                return ResourceManager.GetString("PaymentOptionPlaceholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vaste prijs.
        /// </summary>
        public static string PaymentOptionPrice {
            get {
                return ResourceManager.GetString("PaymentOptionPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Persoonlijk.
        /// </summary>
        public static string Personal {
            get {
                return ResourceManager.GetString("Personal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} van {1}.
        /// </summary>
        public static string PersonOfOrganization {
            get {
                return ResourceManager.GetString("PersonOfOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefoonnummer.
        /// </summary>
        public static string PhoneNumber {
            get {
                return ResourceManager.GetString("PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afbeelding.
        /// </summary>
        public static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto&apos;s.
        /// </summary>
        public static string Photos {
            get {
                return ResourceManager.GetString("Photos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geplaatst door.
        /// </summary>
        public static string PlacedBy {
            get {
                return ResourceManager.GetString("PlacedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string PostalCode {
            get {
                return ResourceManager.GetString("PostalCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levering (Ik ga naar mijn buurtgenoot toe.).
        /// </summary>
        public static string PreferenceDelivery {
            get {
                return ResourceManager.GetString("PreferenceDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Via de post.
        /// </summary>
        public static string PreferenceMail {
            get {
                return ResourceManager.GetString("PreferenceMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Online afhandelen.
        /// </summary>
        public static string PreferenceOnline {
            get {
                return ResourceManager.GetString("PreferenceOnline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ophalen (Mijn buurtgenoot komt naar mij toe.).
        /// </summary>
        public static string PreferencePickup {
            get {
                return ResourceManager.GetString("PreferencePickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijs.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prijstype.
        /// </summary>
        public static string PriceType {
            get {
                return ResourceManager.GetString("PriceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je adres zal niet zichtbaar zijn voor anderen..
        /// </summary>
        public static string PrivacyPolicyAddress {
            get {
                return ResourceManager.GetString("PrivacyPolicyAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je e-mailadres zal niet zichtbaar zijn voor anderen..
        /// </summary>
        public static string PrivacyPolicyEmail {
            get {
                return ResourceManager.GetString("PrivacyPolicyEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het wachtwoord moet tenminste 8 tekens lang zijn en 1 hoofdletter en 1 cijfer bevatten. Je wachtwoord wordt versleuteld bewaard..
        /// </summary>
        public static string PrivacyPolicyPassword {
            get {
                return ResourceManager.GetString("PrivacyPolicyPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privé.
        /// </summary>
        public static string Private {
            get {
                return ResourceManager.GetString("Private", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privékring.
        /// </summary>
        public static string PrivateCircle {
            get {
                return ResourceManager.GetString("PrivateCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Besloten buurtplein.
        /// </summary>
        public static string PrivateSquare {
            get {
                return ResourceManager.GetString("PrivateSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional.
        /// </summary>
        public static string Professional {
            get {
                return ResourceManager.GetString("Professional", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profielfoto.
        /// </summary>
        public static string ProfileImage {
            get {
                return ResourceManager.GetString("ProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openbaar.
        /// </summary>
        public static string Public {
            get {
                return ResourceManager.GetString("Public", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openbare kring.
        /// </summary>
        public static string PublicCircle {
            get {
                return ResourceManager.GetString("PublicCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Straal.
        /// </summary>
        public static string Radius {
            get {
                return ResourceManager.GetString("Radius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactie.
        /// </summary>
        public static string Reaction {
            get {
                return ResourceManager.GetString("Reaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaties uit.
        /// </summary>
        public static string ReceiveMailOff {
            get {
                return ResourceManager.GetString("ReceiveMailOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaties aan.
        /// </summary>
        public static string ReceiveMailOn {
            get {
                return ResourceManager.GetString("ReceiveMailOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontvangers.
        /// </summary>
        public static string Receivers {
            get {
                return ResourceManager.GetString("Receivers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bericht ontvangen wanneer mijn taak geaccepteerd word..
        /// </summary>
        public static string ReceivesCircleJobAssigned {
            get {
                return ResourceManager.GetString("ReceivesCircleJobAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bericht ontvangen wanneer er een taak wordt geplaatst in een kring waar ik lid van ben..
        /// </summary>
        public static string ReceivesCircleJobMail {
            get {
                return ResourceManager.GetString("ReceivesCircleJobMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bericht ontvangen wanneer er een bericht wordt geplaatst in een kring waar ik lid van ben..
        /// </summary>
        public static string ReceivesCircleMessageMail {
            get {
                return ResourceManager.GetString("ReceivesCircleMessageMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bericht ontvangen wanneer iemand reageert op mijn advertentie..
        /// </summary>
        public static string ReceivesMarketplaceMail {
            get {
                return ResourceManager.GetString("ReceivesMarketplaceMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ontvang een bericht bij een nieuw leen of hulp verzoek.
        /// </summary>
        public static string ReceivesNewMarketplaceItemMail {
            get {
                return ResourceManager.GetString("ReceivesNewMarketplaceItemMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekoverzicht.
        /// </summary>
        public static string ReceivesWeekMail {
            get {
                return ResourceManager.GetString("ReceivesWeekMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herhaling.
        /// </summary>
        public static string Recurring {
            get {
                return ResourceManager.GetString("Recurring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elke dag (ma-zo).
        /// </summary>
        public static string RecurringDay {
            get {
                return ResourceManager.GetString("RecurringDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herhalen tot.
        /// </summary>
        public static string RecurringEndsAt {
            get {
                return ResourceManager.GetString("RecurringEndsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elke maand.
        /// </summary>
        public static string RecurringMonth {
            get {
                return ResourceManager.GetString("RecurringMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen herhaling.
        /// </summary>
        public static string RecurringNo {
            get {
                return ResourceManager.GetString("RecurringNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elke twee weken.
        /// </summary>
        public static string RecurringTwoWeek {
            get {
                return ResourceManager.GetString("RecurringTwoWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elke week.
        /// </summary>
        public static string RecurringWeek {
            get {
                return ResourceManager.GetString("RecurringWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elke werkdag (ma-vr).
        /// </summary>
        public static string RecurringWorkDay {
            get {
                return ResourceManager.GetString("RecurringWorkDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elk jaar.
        /// </summary>
        public static string RecurringYear {
            get {
                return ResourceManager.GetString("RecurringYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat is je e-mailadres?.
        /// </summary>
        public static string RegisterEmail {
            get {
                return ResourceManager.GetString("RegisterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat is je naam?.
        /// </summary>
        public static string RegisterName {
            get {
                return ResourceManager.GetString("RegisterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzin een wachtwoord.
        /// </summary>
        public static string RegisterPassword {
            get {
                return ResourceManager.GetString("RegisterPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beheerder verwijderen.
        /// </summary>
        public static string RemoveAdmin {
            get {
                return ResourceManager.GetString("RemoveAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijder deze afbeelding bij het bericht..
        /// </summary>
        public static string RemoveAttachment {
            get {
                return ResourceManager.GetString("RemoveAttachment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kringlid verwijderen.
        /// </summary>
        public static string RemoveCircleMember {
            get {
                return ResourceManager.GetString("RemoveCircleMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitnodiging intrekken.
        /// </summary>
        public static string RemoveInvitation {
            get {
                return ResourceManager.GetString("RemoveInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medewerker verwijderen.
        /// </summary>
        public static string RemoveOrganizationMember {
            get {
                return ResourceManager.GetString("RemoveOrganizationMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herhaal deze taak.
        /// </summary>
        public static string RepeatJob {
            get {
                return ResourceManager.GetString("RepeatJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herhaal deze taak elke.
        /// </summary>
        public static string RepeatWeekdays {
            get {
                return ResourceManager.GetString("RepeatWeekdays", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerapporteerd.
        /// </summary>
        public static string Reported {
            get {
                return ResourceManager.GetString("Reported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerapporteerd door.
        /// </summary>
        public static string ReportedBy {
            get {
                return ResourceManager.GetString("ReportedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingediend op.
        /// </summary>
        public static string RequestDate {
            get {
                return ResourceManager.GetString("RequestDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niet tevreden? Je kunt je foto &lt;a href=&quot;{0}&quot; style=&quot;text-decoration: underline&quot;&gt;roteren&lt;/a&gt;..
        /// </summary>
        public static string RotatePhoto {
            get {
                return ResourceManager.GetString("RotatePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zaterdag.
        /// </summary>
        public static string Saturday {
            get {
                return ResourceManager.GetString("Saturday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beheerders toevoegen uit jouw buurt.
        /// </summary>
        public static string SearchAdmins {
            get {
                return ResourceManager.GetString("SearchAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensen toevoegen uit jouw buurt.
        /// </summary>
        public static string SearchUsers {
            get {
                return ResourceManager.GetString("SearchUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconde geleden.
        /// </summary>
        public static string SecondAgo {
            get {
                return ResourceManager.GetString("SecondAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} seconden geleden.
        /// </summary>
        public static string SecondsAgo {
            get {
                return ResourceManager.GetString("SecondsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opnieuw uitnodigen.
        /// </summary>
        public static string SendCircleInvitationReminder {
            get {
                return ResourceManager.GetString("SendCircleInvitationReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opnieuw uitnodigen.
        /// </summary>
        public static string SendOrganizationInvitationReminder {
            get {
                return ResourceManager.GetString("SendOrganizationInvitationReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze berichten mogen door anderen gedeeld worden..
        /// </summary>
        public static string ShareAllDescription {
            get {
                return ResourceManager.GetString("ShareAllDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit bericht mag door anderen gedeeld worden..
        /// </summary>
        public static string ShareDescription {
            get {
                return ResourceManager.GetString("ShareDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In kring.
        /// </summary>
        public static string ShowInCircle {
            get {
                return ResourceManager.GetString("ShowInCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon mijn locatie bij advertenties..
        /// </summary>
        public static string ShowLocation {
            get {
                return ResourceManager.GetString("ShowLocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon mijn locatie bij deze advertentie.
        /// </summary>
        public static string ShowlocationMarketplaceItem {
            get {
                return ResourceManager.GetString("ShowlocationMarketplaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord tonen.
        /// </summary>
        public static string ShowPassword {
            get {
                return ResourceManager.GetString("ShowPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorteer op.
        /// </summary>
        public static string SortBy {
            get {
                return ResourceManager.GetString("SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gestart.
        /// </summary>
        public static string Started {
            get {
                return ResourceManager.GetString("Started", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starttijd.
        /// </summary>
        public static string StartTime {
            get {
                return ResourceManager.GetString("StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onderwerp.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onderwerpen.
        /// </summary>
        public static string Subjects {
            get {
                return ResourceManager.GetString("Subjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ondertitel.
        /// </summary>
        public static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zondag.
        /// </summary>
        public static string Sunday {
            get {
                return ResourceManager.GetString("Sunday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken.
        /// </summary>
        public static string Tasks {
            get {
                return ResourceManager.GetString("Tasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tekst.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Donderdag.
        /// </summary>
        public static string Thursday {
            get {
                return ResourceManager.GetString("Thursday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tegels.
        /// </summary>
        public static string Tiles {
            get {
                return ResourceManager.GetString("Tiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tijd.
        /// </summary>
        public static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel (max. 80 tekens).
        /// </summary>
        public static string TitleActivity {
            get {
                return ResourceManager.GetString("TitleActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titel (max. 70 tekens).
        /// </summary>
        public static string TitleNeighborhoodMessage {
            get {
                return ResourceManager.GetString("TitleNeighborhoodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naar.
        /// </summary>
        public static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to T/m.
        /// </summary>
        public static string ToAge {
            get {
                return ResourceManager.GetString("ToAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vandaag.
        /// </summary>
        public static string Today {
            get {
                return ResourceManager.GetString("Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toggle.
        /// </summary>
        public static string Toggle {
            get {
                return ResourceManager.GetString("Toggle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Morgen.
        /// </summary>
        public static string Tomorrow {
            get {
                return ResourceManager.GetString("Tomorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totaal.
        /// </summary>
        public static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemeente.
        /// </summary>
        public static string Town {
            get {
                return ResourceManager.GetString("Town", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dinsdag.
        /// </summary>
        public static string Tuesday {
            get {
                return ResourceManager.GetString("Tuesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wat voor soort kring is het?.
        /// </summary>
        public static string TypeOfCircle {
            get {
                return ResourceManager.GetString("TypeOfCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string TypeOfMarketplaceItem {
            get {
                return ResourceManager.GetString("TypeOfMarketplaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mailadres.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikers.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrijwilligersorganisatie.
        /// </summary>
        public static string Volunteer {
            get {
                return ResourceManager.GetString("Volunteer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woensdag.
        /// </summary>
        public static string Wednesday {
            get {
                return ResourceManager.GetString("Wednesday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jaar.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} jaar geleden.
        /// </summary>
        public static string YearAgo {
            get {
                return ResourceManager.GetString("YearAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} jaren geleden.
        /// </summary>
        public static string YearsAgo {
            get {
                return ResourceManager.GetString("YearsAgo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gisteren.
        /// </summary>
        public static string Yesterday {
            get {
                return ResourceManager.GetString("Yesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je naam.
        /// </summary>
        public static string YourName {
            get {
                return ResourceManager.GetString("YourName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je buurt.
        /// </summary>
        public static string YourNeighborhood {
            get {
                return ResourceManager.GetString("YourNeighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je e-mailadres.
        /// </summary>
        public static string YourUsername {
            get {
                return ResourceManager.GetString("YourUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcode.
        /// </summary>
        public static string ZipCode {
            get {
                return ResourceManager.GetString("ZipCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postcodes.
        /// </summary>
        public static string ZipCodes {
            get {
                return ResourceManager.GetString("ZipCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account (mobiel nummer).
        /// </summary>
        public static string ZuiderlingAccount {
            get {
                return ResourceManager.GetString("ZuiderlingAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt op dit moment {0} Zuiderlingen te besteden..
        /// </summary>
        public static string ZuiderlingAmount {
            get {
                return ResourceManager.GetString("ZuiderlingAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        public static string ZuiderlingPassword {
            get {
                return ResourceManager.GetString("ZuiderlingPassword", resourceCulture);
            }
        }
    }
}
