//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeeftSamen.Common.InterfaceText {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Notification {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notification() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeeftSamen.Common.InterfaceText.Notification", typeof(Notification).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft de activiteit &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos; toegevoegd..
        /// </summary>
        public static string ActivityAdded {
            get {
                return ResourceManager.GetString("ActivityAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft zich aangemeld voor de activiteit &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos;..
        /// </summary>
        public static string ActivityAttending {
            get {
                return ResourceManager.GetString("ActivityAttending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bent uitgenodigd om mee te doen met de activiteit &apos;&lt;strong&gt;{0}&lt;/strong&gt;&apos;!.
        /// </summary>
        public static string ActivityInvitation {
            get {
                return ResourceManager.GetString("ActivityInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft je uitnodiging voor de activiteit &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos; geaccepteerd..
        /// </summary>
        public static string ActivityInvitationAccepted {
            get {
                return ResourceManager.GetString("ActivityInvitationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft zich afgemeld voor de activiteit &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos;..
        /// </summary>
        public static string ActivityNotAttending {
            get {
                return ResourceManager.GetString("ActivityNotAttending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft gereageerd op de activiteit &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos;..
        /// </summary>
        public static string ActivityReaction {
            get {
                return ResourceManager.GetString("ActivityReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt toegang gekregen tot de kring &apos;&lt;strong&gt;{0}&lt;/strong&gt;&apos;!.
        /// </summary>
        public static string CircleAccepted {
            get {
                return ResourceManager.GetString("CircleAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bent uitgenodigd om lid te worden van de kring &apos;&lt;strong&gt;{0}&lt;/strong&gt;&apos;!.
        /// </summary>
        public static string CircleInvitation {
            get {
                return ResourceManager.GetString("CircleInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft de uitnodiging voor de kring &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos; geaccepteerd..
        /// </summary>
        public static string CircleInvitationAccepted {
            get {
                return ResourceManager.GetString("CircleInvitationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft je uitnodiging voor de kring &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos; geweigerd..
        /// </summary>
        public static string CircleInvitationDeclined {
            get {
                return ResourceManager.GetString("CircleInvitationDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; pakt een taak op in de kring &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos;!.
        /// </summary>
        public static string CircleJobAssigned {
            get {
                return ResourceManager.GetString("CircleJobAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; kan de taak &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos; niet meer doen..
        /// </summary>
        public static string CircleJobUnassigned {
            get {
                return ResourceManager.GetString("CircleJobUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft de kring &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos; verlaten..
        /// </summary>
        public static string CircleMemberLeft {
            get {
                return ResourceManager.GetString("CircleMemberLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft een nieuw bericht geplaatst in de kring &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos;..
        /// </summary>
        public static string CircleMessage {
            get {
                return ResourceManager.GetString("CircleMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft een reactie geplaatst in de kring &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos;..
        /// </summary>
        public static string CircleMessageReaction {
            get {
                return ResourceManager.GetString("CircleMessageReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft een nieuw document in de kring &lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt; geplaatst..
        /// </summary>
        public static string CircleNewDoc {
            get {
                return ResourceManager.GetString("CircleNewDoc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft je een privé bericht gestuurd in de kring &apos;&lt;strong&gt;{1}&lt;/strong&gt;&apos;..
        /// </summary>
        public static string CircleNewEmail {
            get {
                return ResourceManager.GetString("CircleNewEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een nieuwe taak geplaatst in de kring &apos;&lt;strong&gt;{0}&lt;/strong&gt;&apos;..
        /// </summary>
        public static string CircleNewJob {
            get {
                return ResourceManager.GetString("CircleNewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een nieuw &lt;strong&gt;Vraag en Aanbod&lt;/strong&gt; item geplaatst in  &apos;&lt;u&gt;&lt;strong&gt;{0}&lt;/strong&gt;&lt;/u&gt;&apos;..
        /// </summary>
        public static string CircleNewMarketplaceItem {
            get {
                return ResourceManager.GetString("CircleNewMarketplaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft een nieuwe foto in de kring &lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt; geplaatst..
        /// </summary>
        public static string CircleNewPhoto {
            get {
                return ResourceManager.GetString("CircleNewPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft een verzoek gedaan om lid te worden van de kring &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos;..
        /// </summary>
        public static string CircleReqestedToJoin {
            get {
                return ResourceManager.GetString("CircleReqestedToJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je verzoek om lid te worden van de kring &apos;&lt;u&gt;&lt;strong&gt;{0}&lt;/strong&gt;&lt;/u&gt;&apos; is afgewezen..
        /// </summary>
        public static string CircleRequestRejected {
            get {
                return ResourceManager.GetString("CircleRequestRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft de taak &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos; toegevoegd aan de kring &apos;{2}&apos;..
        /// </summary>
        public static string JobAdded {
            get {
                return ResourceManager.GetString("JobAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft bij vraag en aanbod &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos; toegevoegd..
        /// </summary>
        public static string MarketplaceItemAdded {
            get {
                return ResourceManager.GetString("MarketplaceItemAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft hulp nodig bij (een) &lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;..
        /// </summary>
        public static string MarketplaceItemHelp {
            get {
                return ResourceManager.GetString("MarketplaceItemHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; wil graag (een) &lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt; van je lenen..
        /// </summary>
        public static string MarketplaceItemLend {
            get {
                return ResourceManager.GetString("MarketplaceItemLend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft een nieuw bericht geplaatst bij de advertentie &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos;..
        /// </summary>
        public static string MarketplaceReaction {
            get {
                return ResourceManager.GetString("MarketplaceReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft betaald voor de advertentie &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos;..
        /// </summary>
        public static string MarketplaceTransaction {
            get {
                return ResourceManager.GetString("MarketplaceTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} heeft zich aangemeld voor de activiteit &apos;{1}&apos;..
        /// </summary>
        public static string MobileActivityAttending {
            get {
                return ResourceManager.GetString("MobileActivityAttending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} heeft zich afgemeld voor de activiteit &apos;{1}&apos;..
        /// </summary>
        public static string MobileActivityNotAttending {
            get {
                return ResourceManager.GetString("MobileActivityNotAttending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft het buurtbericht &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos; toegevoegd..
        /// </summary>
        public static string NeighborhoodMessageAdded {
            get {
                return ResourceManager.GetString("NeighborhoodMessageAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft gereageerd op het buurtbericht &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos;..
        /// </summary>
        public static string NeighborhoodMessageReaction {
            get {
                return ResourceManager.GetString("NeighborhoodMessageReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je bent uitgenodigd om lid te worden van de organisatie &apos;&lt;strong&gt;{0}&lt;/strong&gt;&apos;!.
        /// </summary>
        public static string OrganizationInvitation {
            get {
                return ResourceManager.GetString("OrganizationInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft je uitnodiging voor de organisatie &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos; geaccepteerd..
        /// </summary>
        public static string OrganizationInvitationAccepted {
            get {
                return ResourceManager.GetString("OrganizationInvitationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft je uitnodiging voor de organisatie &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos; geweigerd..
        /// </summary>
        public static string OrganizationInvitationDeclined {
            get {
                return ResourceManager.GetString("OrganizationInvitationDeclined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een bericht van je onzichtbaar geworden door het verwijderen van de bijdrage in het onderwerp &lt;strong&gt;{0}&lt;/strong&gt;..
        /// </summary>
        public static string RemoveParentReaction {
            get {
                return ResourceManager.GetString("RemoveParentReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een bericht van je verwijderd in het onderwerp &lt;strong&gt;{0}&lt;/strong&gt;..
        /// </summary>
        public static string RemoveReaction {
            get {
                return ResourceManager.GetString("RemoveReaction", resourceCulture);
            }
        }
    }
}
