//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeeftSamen.Common.InterfaceText {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PlaceHolder {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PlaceHolder() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeeftSamen.Common.InterfaceText.PlaceHolder", typeof(PlaceHolder).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle deelnemers.
        /// </summary>
        public static string AllAttendees {
            get {
                return ResourceManager.GetString("AllAttendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal deelnemers.
        /// </summary>
        public static string AttendeesHeading {
            get {
                return ResourceManager.GetString("AttendeesHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to tafel, bankstel, gymschoenen....
        /// </summary>
        public static string BuyStuff {
            get {
                return ResourceManager.GetString("BuyStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul je e-mailadres in....
        /// </summary>
        public static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul één of meerdere e-mailadressen in….
        /// </summary>
        public static string EnterEmailAddresses {
            get {
                return ResourceManager.GetString("EnterEmailAddresses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voornaam....
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik ben op zoek naar....
        /// </summary>
        public static string IAmSearchingfor {
            get {
                return ResourceManager.GetString("IAmSearchingfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodig deelnemers uit.
        /// </summary>
        public static string InviteAttendees {
            get {
                return ResourceManager.GetString("InviteAttendees", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ik heb hulp nodig met....
        /// </summary>
        public static string IRequireHelpWith {
            get {
                return ResourceManager.GetString("IRequireHelpWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achternaam....
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fiets, boormachine, backpack....
        /// </summary>
        public static string LendStuff {
            get {
                return ResourceManager.GetString("LendStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max. 80 karakters.
        /// </summary>
        public static string MaxCharacters {
            get {
                return ResourceManager.GetString("MaxCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pasta, soep, salade....
        /// </summary>
        public static string MealStuff {
            get {
                return ResourceManager.GetString("MealStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to klusje, boodschappen, verhuizen.
        /// </summary>
        public static string NeighbourHelpStuff {
            get {
                return ResourceManager.GetString("NeighbourHelpStuff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaats een nieuw bericht.
        /// </summary>
        public static string PostNewMessage {
            get {
                return ResourceManager.GetString("PostNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plaats een nieuwe reactie.
        /// </summary>
        public static string PostNewReaction {
            get {
                return ResourceManager.GetString("PostNewReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Herhaal wachtwoord.
        /// </summary>
        public static string RepeatPassword {
            get {
                return ResourceManager.GetString("RepeatPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omschrijf hier duidelijk wat je wilt melden.
        /// </summary>
        public static string ReportDescription {
            get {
                return ResourceManager.GetString("ReportDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoek op naam….
        /// </summary>
        public static string SearchByName {
            get {
                return ResourceManager.GetString("SearchByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoek op naam door de hele buurt….
        /// </summary>
        public static string SearchByNameInNeighborhood {
            get {
                return ResourceManager.GetString("SearchByNameInNeighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Typ hier om te zoeken in LeeftSamen.
        /// </summary>
        public static string TypeToSearch {
            get {
                return ResourceManager.GetString("TypeToSearch", resourceCulture);
            }
        }
    }
}
