//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeeftSamen.Common.InterfaceText {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Subject {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Subject() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeeftSamen.Common.InterfaceText.Subject", typeof(Subject).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] Uitnodiging om mee te doen met een activiteit.
        /// </summary>
        public static string ActivityInvitation {
            get {
                return ResourceManager.GetString("ActivityInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] Nieuw bericht in postvak.
        /// </summary>
        public static string CircleEmailMessageReceived {
            get {
                return ResourceManager.GetString("CircleEmailMessageReceived", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] Uitnodiging om lid te worden van een kring.
        /// </summary>
        public static string CircleInvitation {
            get {
                return ResourceManager.GetString("CircleInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] Een uitnodiging verloopt over 2 dagen.
        /// </summary>
        public static string CircleInvitationWarningExpiredate {
            get {
                return ResourceManager.GetString("CircleInvitationWarningExpiredate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] Nieuwe taak in een kring.
        /// </summary>
        public static string CircleJob {
            get {
                return ResourceManager.GetString("CircleJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] Taak wordt opgepakt in een kring.
        /// </summary>
        public static string CircleJobAssigned {
            get {
                return ResourceManager.GetString("CircleJobAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] Taak weer vrijgekomen in een kring.
        /// </summary>
        public static string CircleJobUnassigned {
            get {
                return ResourceManager.GetString("CircleJobUnassigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] Verzoek om lid te worden van een kring.
        /// </summary>
        public static string CircleJoinRequest {
            get {
                return ResourceManager.GetString("CircleJoinRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] {0} heeft hulp nodig bij een {1}. Kan jij helpen?.
        /// </summary>
        public static string CircleMarketPlaceHelpItemGenerated {
            get {
                return ResourceManager.GetString("CircleMarketPlaceHelpItemGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] Er wacht een nieuwe vraag of aanbieding.
        /// </summary>
        public static string CircleMarketPlaceItemGenerated {
            get {
                return ResourceManager.GetString("CircleMarketPlaceItemGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] {0} is op zoek naar een {1}. Heb jij die te leen?.
        /// </summary>
        public static string CircleMarketPlaceLendItemGenerated {
            get {
                return ResourceManager.GetString("CircleMarketPlaceLendItemGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} nodigt je uit voor LeeftSamen!.
        /// </summary>
        public static string InviteUser {
            get {
                return ResourceManager.GetString("InviteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kijk wat ik gezien heb op LeeftSamen!.
        /// </summary>
        public static string LeeftSamenShare {
            get {
                return ResourceManager.GetString("LeeftSamenShare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] Nieuwe reactie op {0}.
        /// </summary>
        public static string MarketplaceReaction {
            get {
                return ResourceManager.GetString("MarketplaceReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] Betaling voor {0}.
        /// </summary>
        public static string MarketplaceTransaction {
            get {
                return ResourceManager.GetString("MarketplaceTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] Er wacht een nieuw bericht.
        /// </summary>
        public static string MessageGenerated {
            get {
                return ResourceManager.GetString("MessageGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] Uitnodiging om lid te worden van jouw organisatie of vereniging.
        /// </summary>
        public static string OrganizationInvitation {
            get {
                return ResourceManager.GetString("OrganizationInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Leeftsamen] Je bericht is verwijderd.
        /// </summary>
        public static string RemoveReaction {
            get {
                return ResourceManager.GetString("RemoveReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] Melding misbruik.
        /// </summary>
        public static string ReportAbuse {
            get {
                return ResourceManager.GetString("ReportAbuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] Nieuw wachtwoord aangevraagd.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] Dit gebeurt in je buurt!.
        /// </summary>
        public static string SendWeeklyActivities {
            get {
                return ResourceManager.GetString("SendWeeklyActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Suggestie] Nieuwe suggestie van {0}.
        /// </summary>
        public static string Suggestion {
            get {
                return ResourceManager.GetString("Suggestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LeeftSamen] Welkom bij LeeftSamen!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
