//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeeftSamen.Common.InterfaceText {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Text {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Text() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeeftSamen.Common.InterfaceText.Text", typeof(Text).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul je postcode en huisnummer in zodat kan worden bepaald in welke buurt je woont..
        /// </summary>
        public static string AddAddressDescription {
            get {
                return ResourceManager.GetString("AddAddressDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak mensen beheerder voor dit buurtplein. Mensen uit jouw buurt voeg je toe door te zoeken in jouw buurt..
        /// </summary>
        public static string AddAdminToSquareInstruction {
            get {
                return ResourceManager.GetString("AddAdminToSquareInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to alles.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het uploaden van afbeeldingen wordt niet op deze versie van je telefoon of tablet ondersteund..
        /// </summary>
        public static string AndroidUploadNotSupported {
            get {
                return ResourceManager.GetString("AndroidUploadNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samen maken we de beste buurt!.
        /// </summary>
        public static string AppLead {
            get {
                return ResourceManager.GetString("AppLead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeeftSamen is het platform van jouw buurt. Alles wat je nodig hebt in de buurt vind je hier..
        /// </summary>
        public static string AppLeadSubText {
            get {
                return ResourceManager.GetString("AppLeadSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Voeg een afbeelding toe.
        /// </summary>
        public static string AttachmentDescription {
            get {
                return ResourceManager.GetString("AttachmentDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Je bent één van de eerste gebruikers in jouw gemeente. Leuk! Je bent dus een echte pionier! &lt;/p&gt;&lt;p&gt;Wil je meehelpen om LeeftSamen bekend te maken binnen jouw gemeente? Meld je dan aan voor het pionierspakket!&lt;/p&gt;&lt;p&gt;Je ontvangt dan een mooi pakket met promotiemateriaal. Zo kun je je buurtgenoten ook enthousiast maken voor LeeftSamen.&lt;/p&gt;.
        /// </summary>
        public static string BecomePioneerDescription {
            get {
                return ResourceManager.GetString("BecomePioneerDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Door je verjaardag in te vullen weten we of je boven de 18 bent. Zo kunnen we er voor zorgen dat je LeeftSamen-ervaring bij je leeftijd past. Deze gegevens zijn niet zichtbaar voor anderen en worden niet gebruikt voor andere doeleinden. Je kunt je gegevens wijzigen bij ‘Mijn profiel’..
        /// </summary>
        public static string BirthDayDescription {
            get {
                return ResourceManager.GetString("BirthDayDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De achtergrondfoto voor de kring.
        /// </summary>
        public static string CircleCoverImageDescription {
            get {
                return ResourceManager.GetString("CircleCoverImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier kun je berichten sturen naar specifieke personen binnen deze kring.&lt;br /&gt;Kies eerst één of meerdere personen waarmee je in gesprek wilt..
        /// </summary>
        public static string CircleEmailNewGroup {
            get {
                return ResourceManager.GetString("CircleEmailNewGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} nodigt je uit om lid te worden van de kring &apos;{1}&apos;..
        /// </summary>
        public static string CircleInvitationMessage {
            get {
                return ResourceManager.GetString("CircleInvitationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omdat je deze kring beheert zie je ook openstaande uitnodigingen, en kun je herinneringen sturen..
        /// </summary>
        public static string CircleMembersAdminSubText {
            get {
                return ResourceManager.GetString("CircleMembersAdminSubText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De profielfoto van de kring.
        /// </summary>
        public static string CircleProfileImageDescription {
            get {
                return ResourceManager.GetString("CircleProfileImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;Uw huidige profiel heeft geen rechten om deze kring te bekijken.&lt;/p&gt;&lt;p&gt;Wissel naar uw persoonlijke account om verder te gaan.&lt;/p&gt;.
        /// </summary>
        public static string CircleProfileNotAllowed {
            get {
                return ResourceManager.GetString("CircleProfileNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je dit bericht wilt verwijderen uit &apos;Postvak IN&apos;?.
        /// </summary>
        public static string CircleRemoveMessage {
            get {
                return ResourceManager.GetString("CircleRemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je dit bericht wilt verwijderen uit &apos;Verzonden berichten&apos;?.
        /// </summary>
        public static string CircleRemoveSendMessage {
            get {
                return ResourceManager.GetString("CircleRemoveSendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze gebruiker zal ook het ledenbestand, de taken en de kring kunnen beheren..
        /// </summary>
        public static string ConfirmGiveMemberCircleAdminRights {
            get {
                return ResourceManager.GetString("ConfirmGiveMemberCircleAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze gebruiker zal ook het organisatieprofiel kunnen beheren en uit naam van de organisatie berichten kunnen plaatsen..
        /// </summary>
        public static string ConfirmGiveMemberOrganizationAdminRights {
            get {
                return ResourceManager.GetString("ConfirmGiveMemberOrganizationAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je {0} een herinnering wilt sturen?.
        /// </summary>
        public static string ConfirmInvitationReminder {
            get {
                return ResourceManager.GetString("ConfirmInvitationReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je kunt geen berichten meer plaatsen in deze kring..
        /// </summary>
        public static string ConfirmLeaveCircle {
            get {
                return ResourceManager.GetString("ConfirmLeaveCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je je volledige profiel wilt verwijderen? Al je gegevens gaan dan verloren. Je kunt dan ook niet meer inloggen. Wil je weer opnieuw inloggen dan zul je een nieuw profiel moeten aanmaken..
        /// </summary>
        public static string ConfirmRemoveAccount {
            get {
                return ResourceManager.GetString("ConfirmRemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het verwijderen van deze activiteit kan niet ongedaan gemaakt worden..
        /// </summary>
        public static string ConfirmRemoveActivity {
            get {
                return ResourceManager.GetString("ConfirmRemoveActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze gebruiker zal geen beheer meer kunnen doen van dit buurtplein..
        /// </summary>
        public static string ConfirmRemoveAdmin {
            get {
                return ResourceManager.GetString("ConfirmRemoveAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze kring en alle aan deze kring gekoppelde gegevens zullen verwijderd worden..
        /// </summary>
        public static string ConfirmRemoveCircle {
            get {
                return ResourceManager.GetString("ConfirmRemoveCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze gebruiker zal geen berichten meer kunnen plaatsen in deze kring..
        /// </summary>
        public static string ConfirmRemoveCircleMember {
            get {
                return ResourceManager.GetString("ConfirmRemoveCircleMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit kan niet meer ongedaan worden gemaakt..
        /// </summary>
        public static string ConfirmRemoveDocument {
            get {
                return ResourceManager.GetString("ConfirmRemoveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je zal dan geen berichten meer ontvangen van dit gesprek..
        /// </summary>
        public static string ConfirmRemoveEmailGroup {
            get {
                return ResourceManager.GetString("ConfirmRemoveEmailGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit feiten alle aan dit feit gekoppelde bestanden zullen verwijderd worden..
        /// </summary>
        public static string ConfirmRemoveFact {
            get {
                return ResourceManager.GetString("ConfirmRemoveFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze taak zal definitief verwijderd worden..
        /// </summary>
        public static string ConfirmRemoveJob {
            get {
                return ResourceManager.GetString("ConfirmRemoveJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het verwijderen van deze advertentie kan niet ongedaan gemaakt worden..
        /// </summary>
        public static string ConfirmRemoveMarketplaceItem {
            get {
                return ResourceManager.GetString("ConfirmRemoveMarketplaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het verwijderen van dit nieuwsbericht kan niet ongedaan gemaakt worden..
        /// </summary>
        public static string ConfirmRemoveNeighborhoodMessage {
            get {
                return ResourceManager.GetString("ConfirmRemoveNeighborhoodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het verwijderen van deze reactie kan niet ongedaan gemaakt worden..
        /// </summary>
        public static string ConfirmRemoveNeighborhoodMessageReaction {
            get {
                return ResourceManager.GetString("ConfirmRemoveNeighborhoodMessageReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze organisatie en alle gekoppelde gegevens zullen verwijderd worden..
        /// </summary>
        public static string ConfirmRemoveOrganization {
            get {
                return ResourceManager.GetString("ConfirmRemoveOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze gebruiker zal geen berichten meer kunnen plaatsen uit naam van de organisatie..
        /// </summary>
        public static string ConfirmRemoveOrganizationMember {
            get {
                return ResourceManager.GetString("ConfirmRemoveOrganizationMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit kan niet meer ongedaan worden gemaakt..
        /// </summary>
        public static string ConfirmRemovePhoto {
            get {
                return ResourceManager.GetString("ConfirmRemovePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle foto&apos;s in dit album zullen verwijderd worden..
        /// </summary>
        public static string ConfirmRemovePhotoAlbum {
            get {
                return ResourceManager.GetString("ConfirmRemovePhotoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze reactie zal verwijderd worden..
        /// </summary>
        public static string ConfirmRemoveReaction {
            get {
                return ResourceManager.GetString("ConfirmRemoveReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit onderwerp zal verwijderd worden.
        /// </summary>
        public static string ConfirmRemoveSubject {
            get {
                return ResourceManager.GetString("ConfirmRemoveSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De beheerders zullen zo snel mogelijk naar de reactie kijken..
        /// </summary>
        public static string ConfirmReportReaction {
            get {
                return ResourceManager.GetString("ConfirmReportReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berichten in deze kring kunnen alleen door de leden van de kring gelezen worden..
        /// </summary>
        public static string ConfirmSetCirclePrivate {
            get {
                return ResourceManager.GetString("ConfirmSetCirclePrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle berichten van deze kring zullen openbaar worden!.
        /// </summary>
        public static string ConfirmSetCirclePublic {
            get {
                return ResourceManager.GetString("ConfirmSetCirclePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je wordt weer gewaarschuwd bij nieuwe activiteiten in deze kring.
        /// </summary>
        public static string ConfirmStartCircleEmails {
            get {
                return ResourceManager.GetString("ConfirmStartCircleEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je wordt niet meer gewaarschuwd bij nieuwe activiteiten in deze kring.
        /// </summary>
        public static string ConfirmStopCircleEmails {
            get {
                return ResourceManager.GetString("ConfirmStopCircleEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to U kunt maar 1 keer stemmen..
        /// </summary>
        public static string ConfirmVoteAction {
            get {
                return ResourceManager.GetString("ConfirmVoteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruikers met een verwijderde postcode zullen niet langer meer bij dit buurtplein kunnen komen..
        /// </summary>
        public static string ConfirmZipCodeDelete {
            get {
                return ResourceManager.GetString("ConfirmZipCodeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De overschrijving zal hiermee definitief uitgevoerd worden..
        /// </summary>
        public static string ConfirmZuiderlingTransaction {
            get {
                return ResourceManager.GetString("ConfirmZuiderlingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lees verder....
        /// </summary>
        public static string ContinueReading {
            get {
                return ResourceManager.GetString("ContinueReading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak een nieuw profiel aan..
        /// </summary>
        public static string CreateAccountDescription {
            get {
                return ResourceManager.GetString("CreateAccountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} km bij jou vandaan.
        /// </summary>
        public static string DistanceFromYou {
            get {
                return ResourceManager.GetString("DistanceFromYou", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h3&gt;Korte uitleg&lt;/h3&gt;&lt;p&gt;Hier kan een korte uitleg getoond worden voor dit formulier&lt;/p&gt;.
        /// </summary>
        public static string EditItemExplanation {
            get {
                return ResourceManager.GetString("EditItemExplanation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je e-mailadres is bevestigd..
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn op dit moment geen feiten toegevoegd aan dit buurtplein..
        /// </summary>
        public static string FactsEmpty {
            get {
                return ResourceManager.GetString("FactsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coöperatieve vereniging LeeftSamen - Alle rechten voorbehouden.
        /// </summary>
        public static string FooterAllRightsReserved {
            get {
                return ResourceManager.GetString("FooterAllRightsReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volg ons op Twitter.
        /// </summary>
        public static string FooterFollowUsOnTwitter {
            get {
                return ResourceManager.GetString("FooterFollowUsOnTwitter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to volg ons op YouTube.
        /// </summary>
        public static string FooterFollowUsOnYouTube {
            get {
                return ResourceManager.GetString("FooterFollowUsOnYouTube", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to stuur ons een e-mail.
        /// </summary>
        public static string FooterSendUsAnEmail {
            get {
                return ResourceManager.GetString("FooterSendUsAnEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to algemene voorwaarden.
        /// </summary>
        public static string FooterTermsAndConditions {
            get {
                return ResourceManager.GetString("FooterTermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul het e-mailadres van jouw LeeftSamen-profiel in en we sturen je de instructies voor het instellen van een nieuw wachtwoord..
        /// </summary>
        public static string ForgotPasswordInstruction {
            get {
                return ResourceManager.GetString("ForgotPasswordInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het emailadres wat je hebt ingetypt bestaat niet..
        /// </summary>
        public static string ForgotPasswordInstructionError {
            get {
                return ResourceManager.GetString("ForgotPasswordInstructionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een e-mail naar je gestuurd om je wachtwoord opnieuw in te stellen..
        /// </summary>
        public static string ForgotPasswordInstructionsSend {
            get {
                return ResourceManager.GetString("ForgotPasswordInstructionsSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weten wat er in je buurt te doen is? Bekijk de buurtagenda of maak zelf een activiteit aan..
        /// </summary>
        public static string InfoActivities {
            get {
                return ResourceManager.GetString("InfoActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wil je met een groep mensen een kring vormen rond een thema of een activiteit? Of wil je een ondersteuningskring vormen rondom iemand? Door een kring aan te maken wordt samen iets regelen of organiseren nog gemakkelijker. Er zijn twee mogelijkheden: Je kunt een publieke kring of een privékring aanmaken. Een publieke kring is ook voor andere mensen zichtbaar. Iedereen die de kring ziet kan zich aanmelden als lid. Jij bepaalt uiteindelijk of iemand lid mag worden of niet. Een privékring daarentegen is voor ni [rest of string was truncated]&quot;;.
        /// </summary>
        public static string InfoCircles {
            get {
                return ResourceManager.GetString("InfoCircles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je kunt je bericht wijzigen tot {0}..
        /// </summary>
        public static string InfoEditMessage {
            get {
                return ResourceManager.GetString("InfoEditMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je kunt je reactie wijzigen tot {0}.
        /// </summary>
        public static string InfoEditReaction {
            get {
                return ResourceManager.GetString("InfoEditReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hier vind je alle openstaande uitnodigingen voor zowel organisaties als kringen..
        /// </summary>
        public static string InfoInvitations {
            get {
                return ResourceManager.GetString("InfoInvitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heb je wat nodig of wat over? Wil je iets van iemand lenen of ben je bereid iets uit te lenen? Of kan je iemand tot hulp zijn of heb je hulp nodig? Regel het bij vraag en aanbod!.
        /// </summary>
        public static string InfoMarketplace {
            get {
                return ResourceManager.GetString("InfoMarketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lees wat je buurtgenoten en organisaties, clubs, verenigingen en dergelijke in je buurt te melden hebben. Of schrijf zelf iets!.
        /// </summary>
        public static string InfoNeighborhoodMessages {
            get {
                return ResourceManager.GetString("InfoNeighborhoodMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wil je weten welke organisaties, clubs, verenigingen en dergelijke in je buurt actief zijn? En wil je weten wat ze doen en welke producten en diensten ze aanbieden? Vind alles in de buurtgids!.
        /// </summary>
        public static string InfoOrganizations {
            get {
                return ResourceManager.GetString("InfoOrganizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeeftSamen is gratis en van alle gebruikers.
        /// </summary>
        public static string IntroHome {
            get {
                return ResourceManager.GetString("IntroHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je kunt meerdere mensen tegelijkertijd uitnodigen door de e-mailadressen te scheiden met een puntkomma (;), een komma (,) of een spatie..
        /// </summary>
        public static string InviteMultipleUsersByEmail {
            get {
                return ResourceManager.GetString("InviteMultipleUsersByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodig mensen uit voor deze activiteit. Mensen die nog geen profiel hebben op LeeftSamen of die niet in jouw buurt wonen kun je uitnodigen via e-mail. Mensen die al wel een profiel hebben en in jouw buurt wonen kun je uitnodigen door hun profiel aan te klikken..
        /// </summary>
        public static string InviteUsersToActivityInstruction {
            get {
                return ResourceManager.GetString("InviteUsersToActivityInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodig mensen uit voor deze kring. Mensen die nog geen profiel hebben op LeeftSamen of die niet in jouw buurt wonen kun je uitnodigen via e-mail. Mensen uit jouw buurt voeg je toe door te zoeken in jouw buurt..
        /// </summary>
        public static string InviteUsersToCircleInstruction {
            get {
                return ResourceManager.GetString("InviteUsersToCircleInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nodig mensen uit voor deze organisatie. Mensen die nog geen profiel hebben op LeeftSamen of die niet in jouw buurt wonen kun je uitnodigen via e-mail. Mensen uit jouw buurt voeg je toe door te zoeken in jouw buurt..
        /// </summary>
        public static string InviteUsersToOrganizationInstruction {
            get {
                return ResourceManager.GetString("InviteUsersToOrganizationInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Samen maken we de beste buurt! Nodig je buren, familie, vrienden en kennissen uit voor LeeftSamen. Zo kunnen ook zij ervaren hoe leuk hun buurt is! &lt;br /&gt;&lt;br /&gt;Vul hieronder hun e-mailadressen in en je kunt ze direct een uitnodiging sturen..
        /// </summary>
        public static string InviteUsersToWebsite {
            get {
                return ResourceManager.GetString("InviteUsersToWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laatste advertentie in.
        /// </summary>
        public static string LatestItemIn {
            get {
                return ResourceManager.GetString("LatestItemIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This account has been locked out, please try again later..
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt; Leuk dat je ook een profiel hebt aangemaakt op LeeftSamen. We hopen dat je hier alles vindt dat je nodig hebt in jouw buurt. Wij doen ons best om het LeeftSamen-platform samen met jou beter te maken. We hopen dan ook dat je suggesties voor ons hebt, die kun je via de oranje knop “ suggesties&quot; aan ons doorgeven.&lt;/p&gt;
        ///&lt;p&gt;Verder raden we je aan om direct een profielfoto toe te voegen. Dat maakt het een stuk gezelliger in de buurt!&lt;/p&gt;
        ///&lt;p class=&quot;hidden-xs&quot;&gt;Door te klikken op de vraagtekens ontdek je snel a [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LoginIntro {
            get {
                return ResourceManager.GetString("LoginIntro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze advertentie is privé..
        /// </summary>
        public static string MarketPlaceItemIsPrivate {
            get {
                return ResourceManager.GetString("MarketPlaceItemIsPrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heb je nog geen profiel? Maak dan &lt;a href=&quot;{0}&quot;&gt;hier&lt;/a&gt; een profiel aan..
        /// </summary>
        public static string NoAccountCreateOne {
            get {
                return ResourceManager.GetString("NoAccountCreateOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn nog geen albums toegevoegd aan deze kring..
        /// </summary>
        public static string NoAlbumsFound {
            get {
                return ResourceManager.GetString("NoAlbumsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn nog geen documenten toegevoegd aan deze kring.
        /// </summary>
        public static string NoDocumentsFound {
            get {
                return ResourceManager.GetString("NoDocumentsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn nog geen onderwerpen aangemaakt.
        /// </summary>
        public static string NoForumSubjects {
            get {
                return ResourceManager.GetString("NoForumSubjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn geen berichten gevonden.
        /// </summary>
        public static string NoMessagesFound {
            get {
                return ResourceManager.GetString("NoMessagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn nog geen foto&apos;s toegevoegd aan dit album..
        /// </summary>
        public static string NoPhotosFound {
            get {
                return ResourceManager.GetString("NoPhotosFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn nog geen reacties geplaatst.
        /// </summary>
        public static string NoReactions {
            get {
                return ResourceManager.GetString("NoReactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn op dit moment geen geraporteerde reacties..
        /// </summary>
        public static string NoReportedReactions {
            get {
                return ResourceManager.GetString("NoReportedReactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jouw gemeente doet nog niet mee met LeeftSamen. Je kan LeeftSamen wel volledig gebruiken, maar er is nog geen ondersteuning beschikbaar vanuit jouw gemeente..
        /// </summary>
        public static string NotActiveInCity {
            get {
                return ResourceManager.GetString("NotActiveInCity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeeftSamen gebruikt notificaties zodat we je gemakkelijk op de hoogte kunnen houden van alle belangrijke dingen die er in jouw buurt gebeuren. Je kunt je instellingen voor het ontvangen van notificaties helemaal naar jouw wens aanpassen zodat je alleen notificaties ontvangt van de dingen die jij belangrijk vindt. 
        ///Hieronder kun je aanvinken voor welke onderwerpen je graag notificaties wilt ontvangen. De linkerkolom staat voor notificaties op het platform en de rechterkolom staat voor notificaties op je tel [rest of string was truncated]&quot;;.
        /// </summary>
        public static string NotificationSettings {
            get {
                return ResourceManager.GetString("NotificationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruik het menu rechtsbovenin om het platform te doorzoeken..
        /// </summary>
        public static string NoTimelineNavigationTip {
            get {
                return ResourceManager.GetString("NoTimelineNavigationTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je kunt geen privebericht sturen..
        /// </summary>
        public static string NotSendMessageToMarketplaceItemOwner {
            get {
                return ResourceManager.GetString("NotSendMessageToMarketplaceItemOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nog geen advertenties in.
        /// </summary>
        public static string NotYetItemsIn {
            get {
                return ResourceManager.GetString("NotYetItemsIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heb je nog geen profiel op LeeftSamen?.
        /// </summary>
        public static string NotYetRegistered {
            get {
                return ResourceManager.GetString("NotYetRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string Or {
            get {
                return ResourceManager.GetString("Or", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je kunt één of meerdere thema&apos;s aanvinken..
        /// </summary>
        public static string OrganisationThemesInstruction {
            get {
                return ResourceManager.GetString("OrganisationThemesInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef aan met welke thema&apos;s je organisatie zich bezig houdt..
        /// </summary>
        public static string OrganisationThemesSettingsInstruction {
            get {
                return ResourceManager.GetString("OrganisationThemesSettingsInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je kunt één of meerdere wijken aanvinken..
        /// </summary>
        public static string OrganizationActiveInDistrictsInstruction {
            get {
                return ResourceManager.GetString("OrganizationActiveInDistrictsInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een overzicht van alle activiteiten, geplaatst door {0}..
        /// </summary>
        public static string OrganizationActivityFeed {
            get {
                return ResourceManager.GetString("OrganizationActivityFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vul je contactgegevens in..
        /// </summary>
        public static string OrganizationContactInformationInstruction {
            get {
                return ResourceManager.GetString("OrganizationContactInformationInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algemene informatie over je organisatie.
        /// </summary>
        public static string OrganizationGeneralInformationInstruction {
            get {
                return ResourceManager.GetString("OrganizationGeneralInformationInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een overzicht van alle berichten, geplaatst door {0}..
        /// </summary>
        public static string OrganizationMessagesFeed {
            get {
                return ResourceManager.GetString("OrganizationMessagesFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geef aan in welke omgeving je organisatie actief is..
        /// </summary>
        public static string OrganizationNeighborhoodSettingsInstruction {
            get {
                return ResourceManager.GetString("OrganizationNeighborhoodSettingsInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze omschrijving komt op je profiel te staan. Met deze omschrijving kan je in maximaal 600 karakters een bredere omschrijving geven van je product..
        /// </summary>
        public static string OrganizationProductFullTextInstruction {
            get {
                return ResourceManager.GetString("OrganizationProductFullTextInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze omschrijving komt op de overzichtspagina te staan. Presenteer in maximaal 140 karakters je dienst. Deze omschrijving kan de bezoeker overhalen om meer over je dienst te weten te willen komen..
        /// </summary>
        public static string OrganizationProductIntroductionTextInstruction {
            get {
                return ResourceManager.GetString("OrganizationProductIntroductionTextInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrganizationProductsInstruction {
            get {
                return ResourceManager.GetString("OrganizationProductsInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrganizationProductTitleInstruction {
            get {
                return ResourceManager.GetString("OrganizationProductTitleInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je kan altijd een aanvraag indienen om jouw organisatie ook een plek te geven op LeeftSamen..
        /// </summary>
        public static string OrganizationRequest {
            get {
                return ResourceManager.GetString("OrganizationRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze omschrijving komt op je profiel te staan. Met deze omschrijving kan je in maximaal 600 karakters een bredere omschrijving geven van je dienst..
        /// </summary>
        public static string OrganizationServiceFullTextInstruction {
            get {
                return ResourceManager.GetString("OrganizationServiceFullTextInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze omschrijving komt op de overzichtspagina te staan. Presenteer in maximaal 140 karakters je dienst. Deze omschrijving kan de bezoeker overhalen meer over je dienst te weten te willen komen..
        /// </summary>
        public static string OrganizationServiceIntroductionTextInstruction {
            get {
                return ResourceManager.GetString("OrganizationServiceIntroductionTextInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrganizationServicesInstruction {
            get {
                return ResourceManager.GetString("OrganizationServicesInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string OrganizationServiceTitleInstruction {
            get {
                return ResourceManager.GetString("OrganizationServiceTitleInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft de gebruiker &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos; uitgenodigd om lid te worden van de kring..
        /// </summary>
        public static string OverviewInvited {
            get {
                return ResourceManager.GetString("OverviewInvited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; wilt lid worden van de kring..
        /// </summary>
        public static string OverviewJoinRequest {
            get {
                return ResourceManager.GetString("OverviewJoinRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft een nieuwe activiteit geplaatst genaamd &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos;..
        /// </summary>
        public static string OverviewNewAction {
            get {
                return ResourceManager.GetString("OverviewNewAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft een nieuw bericht geplaatst..
        /// </summary>
        public static string OverviewNewMessage {
            get {
                return ResourceManager.GetString("OverviewNewMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft een nieuwe foto geplaatst..
        /// </summary>
        public static string OverviewNewPhoto {
            get {
                return ResourceManager.GetString("OverviewNewPhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;strong&gt;{0}&lt;/strong&gt; heeft een nieuwe taak geplaatst genaamd &apos;&lt;u&gt;&lt;strong&gt;{1}&lt;/strong&gt;&lt;/u&gt;&apos;..
        /// </summary>
        public static string OverviewNewTask {
            get {
                return ResourceManager.GetString("OverviewNewTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je wachtwoord moet minimaal 8 karakters lang zijn..
        /// </summary>
        public static string PasswordDescription {
            get {
                return ResourceManager.GetString("PasswordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als u dit bericht vast zet zal het boven aan in de lijst van de berichten gaan staan..
        /// </summary>
        public static string PinConfirmation {
            get {
                return ResourceManager.GetString("PinConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Levering (Ik kom het bij je brengen.).
        /// </summary>
        public static string PreferenceDelivery {
            get {
                return ResourceManager.GetString("PreferenceDelivery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ophalen (Je kan bij mij langskomen.).
        /// </summary>
        public static string PreferencePickup {
            get {
                return ResourceManager.GetString("PreferencePickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kies een duidelijke foto van jezelf, zodat anderen je makkelijk kunnen vinden..
        /// </summary>
        public static string ProfileImageDescription {
            get {
                return ResourceManager.GetString("ProfileImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze reactie is verwijderd..
        /// </summary>
        public static string ReactionDeleted {
            get {
                return ResourceManager.GetString("ReactionDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze gebruiker zal het ledenbestand, de taken en de kring niet meer kunnen beheren..
        /// </summary>
        public static string RemoveMemberCircleAdminRights {
            get {
                return ResourceManager.GetString("RemoveMemberCircleAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze gebruiker zal het organisatieprofiel niet meer kunnen beheren en geen berichten meer uit naam van de organisatie kunnen plaatsen..
        /// </summary>
        public static string RemoveMemberOrganizationAdminRights {
            get {
                return ResourceManager.GetString("RemoveMemberOrganizationAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwijder het {0} album.
        /// </summary>
        public static string RemovePhotoAlbum {
            get {
                return ResourceManager.GetString("RemovePhotoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ongewenst gedrag, spam-berichten en ander misbruik op deze pagina kun je hier melden. LeeftSamen neemt elke melding serieus..
        /// </summary>
        public static string ReportAbuse {
            get {
                return ResourceManager.GetString("ReportAbuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gezocht op:.
        /// </summary>
        public static string SearchedOn {
            get {
                return ResourceManager.GetString("SearchedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stel de grootte van je buurt in..
        /// </summary>
        public static string SetNeighborhoodRadiusDescription {
            get {
                return ResourceManager.GetString("SetNeighborhoodRadiusDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deel deze activiteit..
        /// </summary>
        public static string ShareActivity {
            get {
                return ResourceManager.GetString("ShareActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deel deze advertentie..
        /// </summary>
        public static string ShareMarketPlaceItem {
            get {
                return ResourceManager.GetString("ShareMarketPlaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deel dit bericht.
        /// </summary>
        public static string ShareNews {
            get {
                return ResourceManager.GetString("ShareNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alleen jij hebt dit bericht ontvangen..
        /// </summary>
        public static string SingleReciever {
            get {
                return ResourceManager.GetString("SingleReciever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De achtergrondfoto voor het buurtplein.
        /// </summary>
        public static string SquareCoverImageDescription {
            get {
                return ResourceManager.GetString("SquareCoverImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De profielfoto van het buurtplein.
        /// </summary>
        public static string SquareProfileImageDescription {
            get {
                return ResourceManager.GetString("SquareProfileImageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Als je dit bericht los maakt zal het bericht niet meer bovenaan in de lijst van berichten staan. (Tenzij het een nieuw bericht is natuurlijk!).
        /// </summary>
        public static string UnpinConfirmation {
            get {
                return ResourceManager.GetString("UnpinConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bekijk.
        /// </summary>
        public static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welkom {0}!.
        /// </summary>
        public static string WelcomeUser {
            get {
                return ResourceManager.GetString("WelcomeUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to binnen.
        /// </summary>
        public static string Within {
            get {
                return ResourceManager.GetString("Within", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze personen hebben je de bevoegdheid gegeven om namens hen berichten te plaatsen..
        /// </summary>
        public static string YouAreBuddyOf {
            get {
                return ResourceManager.GetString("YouAreBuddyOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deze personen heb je de bevoegdheid gegeven om namens jou berichten te plaatsen..
        /// </summary>
        public static string YourBuddies {
            get {
                return ResourceManager.GetString("YourBuddies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;De grootte van je buurt bepaalt welke berichten en buurtgenoten je ziet.&lt;/p&gt;&lt;p&gt;Gebruik het menu of de schuif om zelf de grootte van je buurt in te stellen.&lt;/p&gt;.
        /// </summary>
        public static string YourNeighborhoodInstruction {
            get {
                return ResourceManager.GetString("YourNeighborhoodInstruction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De Zuiderling is een ruilmunt in Rotterdam. Je kunt Zuiderlingen verdienen én uitgeven  door met je talent een ander te helpen of door het talent van een ander voor jezelf in te zetten.  Je kunt je Zuiderling account &lt;a href=&quot;http://www.dezuiderling.nl/meedoen/meld-je-aan-direct-sms-de-helpdesk&quot; target=&quot;_blank&quot;&gt;hier&lt;/a&gt; aanvragen en koppelen aan je LeeftSamen-profiel. Zo kun je gemakkelijk Zuiderlingen verdienen én uitgeven op het LeeftSamen-platform!&lt;br /&gt;&lt;br /&gt; Je kunt je account koppelen door hieronder j [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ZuiderlingInfo {
            get {
                return ResourceManager.GetString("ZuiderlingInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Om deze advertentie te betalen is een zuiderling account nodig..
        /// </summary>
        public static string ZuiderlingRequiredForTransaction {
            get {
                return ResourceManager.GetString("ZuiderlingRequiredForTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeeftSamen betaling.
        /// </summary>
        public static string ZuiderlingServiceTransactionDescription {
            get {
                return ResourceManager.GetString("ZuiderlingServiceTransactionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertentie betaald..
        /// </summary>
        public static string ZuiderlingTransactionPaid {
            get {
                return ResourceManager.GetString("ZuiderlingTransactionPaid", resourceCulture);
            }
        }
    }
}
