//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LeeftSamen.Common.InterfaceText {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Title {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Title() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LeeftSamen.Common.InterfaceText.Title", typeof(Title).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Over deze kring.
        /// </summary>
        public static string AboutThisCircle {
            get {
                return ResourceManager.GetString("AboutThisCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen toegang.
        /// </summary>
        public static string AccessDenied {
            get {
                return ResourceManager.GetString("AccessDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locatieweergave.
        /// </summary>
        public static string AccountLocationLabel {
            get {
                return ResourceManager.GetString("AccountLocationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buurtagenda.
        /// </summary>
        public static string Activities {
            get {
                return ResourceManager.GetString("Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteit.
        /// </summary>
        public static string Activity {
            get {
                return ResourceManager.GetString("Activity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensen beheerder maken van je buurtplein.
        /// </summary>
        public static string AddAdminToSquare {
            get {
                return ResourceManager.GetString("AddAdminToSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin.
        /// </summary>
        public static string Admin {
            get {
                return ResourceManager.GetString("Admin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string Agenda {
            get {
                return ResourceManager.GetString("Agenda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeeftSamen.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foute aanvraag.
        /// </summary>
        public static string BadRequest {
            get {
                return ResourceManager.GetString("BadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buddy&apos;s.
        /// </summary>
        public static string Buddies {
            get {
                return ResourceManager.GetString("Buddies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteiten.
        /// </summary>
        public static string BulkActivities {
            get {
                return ResourceManager.GetString("BulkActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie.
        /// </summary>
        public static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig je profielinstellingen.
        /// </summary>
        public static string ChangeAccountSettings {
            get {
                return ResourceManager.GetString("ChangeAccountSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig foruminstellingen.
        /// </summary>
        public static string ChangeForum {
            get {
                return ResourceManager.GetString("ChangeForum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kringprofiel aanpassen.
        /// </summary>
        public static string ChangeMemberProfile {
            get {
                return ResourceManager.GetString("ChangeMemberProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig je naam.
        /// </summary>
        public static string ChangeName {
            get {
                return ResourceManager.GetString("ChangeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig je buurtinstellingen.
        /// </summary>
        public static string ChangeNeighborhood {
            get {
                return ResourceManager.GetString("ChangeNeighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig je notificatie instellingen.
        /// </summary>
        public static string ChangeNotification {
            get {
                return ResourceManager.GetString("ChangeNotification", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig je wachtwoord.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een veilig wachtwoord bestaat uit zoveel mogelijk verschillende tekens..
        /// </summary>
        public static string ChangePasswordForm {
            get {
                return ResourceManager.GetString("ChangePasswordForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig je profielfoto.
        /// </summary>
        public static string ChangeProfileImage {
            get {
                return ResourceManager.GetString("ChangeProfileImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig het buurtplein.
        /// </summary>
        public static string ChangeSquare {
            get {
                return ResourceManager.GetString("ChangeSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig de buurtplein instellingen.
        /// </summary>
        public static string ChangeSquareSettings {
            get {
                return ResourceManager.GetString("ChangeSquareSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig je e-mailadres.
        /// </summary>
        public static string ChangeUsername {
            get {
                return ResourceManager.GetString("ChangeUsername", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig toegestane postcodes.
        /// </summary>
        public static string ChangeZipCodes {
            get {
                return ResourceManager.GetString("ChangeZipCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agenda.
        /// </summary>
        public static string CircleActivities {
            get {
                return ResourceManager.GetString("CircleActivities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Albums.
        /// </summary>
        public static string CircleAlbums {
            get {
                return ResourceManager.GetString("CircleAlbums", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kringgegevens.
        /// </summary>
        public static string CircleData {
            get {
                return ResourceManager.GetString("CircleData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bepaal zelf hoe je kring eruit ziet..
        /// </summary>
        public static string CircleDesign {
            get {
                return ResourceManager.GetString("CircleDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documenten.
        /// </summary>
        public static string CircleDocuments {
            get {
                return ResourceManager.GetString("CircleDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foto&apos;s.
        /// </summary>
        public static string CirclePhotos {
            get {
                return ResourceManager.GetString("CirclePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bericht Verwijderen.
        /// </summary>
        public static string CircleRemoveMessage {
            get {
                return ResourceManager.GetString("CircleRemoveMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kringen.
        /// </summary>
        public static string Circles {
            get {
                return ResourceManager.GetString("Circles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze gebruiker beheerrechten wilt geven?.
        /// </summary>
        public static string ConfirmGiveMemberAdminRights {
            get {
                return ResourceManager.GetString("ConfirmGiveMemberAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bevestig herinnering.
        /// </summary>
        public static string ConfirmInvitationReminder {
            get {
                return ResourceManager.GetString("ConfirmInvitationReminder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze kring wilt verlaten?.
        /// </summary>
        public static string ConfirmLeaveCircle {
            get {
                return ResourceManager.GetString("ConfirmLeaveCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze activiteit wilt verwijderen?.
        /// </summary>
        public static string ConfirmRemoveActivity {
            get {
                return ResourceManager.GetString("ConfirmRemoveActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze beheerder wilt verwijderen?.
        /// </summary>
        public static string ConfirmRemoveAdmin {
            get {
                return ResourceManager.GetString("ConfirmRemoveAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze kring wilt verwijderen?.
        /// </summary>
        public static string ConfirmRemoveCircle {
            get {
                return ResourceManager.GetString("ConfirmRemoveCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je dit kringlid uit de kring wilt verwijderen?.
        /// </summary>
        public static string ConfirmRemoveCircleMember {
            get {
                return ResourceManager.GetString("ConfirmRemoveCircleMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je dit document wilt verwijderen?.
        /// </summary>
        public static string ConfirmRemoveDocument {
            get {
                return ResourceManager.GetString("ConfirmRemoveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je dit gesprek wilt verlaten?.
        /// </summary>
        public static string ConfirmRemoveEmailGroup {
            get {
                return ResourceManager.GetString("ConfirmRemoveEmailGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je dit feit wilt verwijderen?.
        /// </summary>
        public static string ConfirmRemoveFact {
            get {
                return ResourceManager.GetString("ConfirmRemoveFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze taak wilt verwijderen?.
        /// </summary>
        public static string ConfirmRemoveJob {
            get {
                return ResourceManager.GetString("ConfirmRemoveJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze advertentie wilt verwijderen?.
        /// </summary>
        public static string ConfirmRemoveMarketplaceItem {
            get {
                return ResourceManager.GetString("ConfirmRemoveMarketplaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je dit nieuwsbericht wilt verwijderen?.
        /// </summary>
        public static string ConfirmRemoveNeighborhoodMessage {
            get {
                return ResourceManager.GetString("ConfirmRemoveNeighborhoodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze reactie wilt verwijderen?.
        /// </summary>
        public static string ConfirmRemoveNeighborhoodMessageReaction {
            get {
                return ResourceManager.GetString("ConfirmRemoveNeighborhoodMessageReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze organisatie wilt verwijderen?.
        /// </summary>
        public static string ConfirmRemoveOrganization {
            get {
                return ResourceManager.GetString("ConfirmRemoveOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze medewerker wilt verwijderen?.
        /// </summary>
        public static string ConfirmRemoveOrganizationMember {
            get {
                return ResourceManager.GetString("ConfirmRemoveOrganizationMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze foto wilt verwijderen?.
        /// </summary>
        public static string ConfirmRemovePhoto {
            get {
                return ResourceManager.GetString("ConfirmRemovePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je dit fotoalbum wilt verwijderen?.
        /// </summary>
        public static string ConfirmRemovePhotoAlbum {
            get {
                return ResourceManager.GetString("ConfirmRemovePhotoAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze reactie wilt verwijderen?.
        /// </summary>
        public static string ConfirmRemoveReaction {
            get {
                return ResourceManager.GetString("ConfirmRemoveReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je dit onderwerp wilt verwijderen?.
        /// </summary>
        public static string ConfirmRemoveSubject {
            get {
                return ResourceManager.GetString("ConfirmRemoveSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze reactie wilt rapporteren?.
        /// </summary>
        public static string ConfirmReportReaction {
            get {
                return ResourceManager.GetString("ConfirmReportReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze kring privé wilt maken?.
        /// </summary>
        public static string ConfirmSetCirclePrivate {
            get {
                return ResourceManager.GetString("ConfirmSetCirclePrivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze kring openbaar wilt maken?.
        /// </summary>
        public static string ConfirmSetCirclePublic {
            get {
                return ResourceManager.GetString("ConfirmSetCirclePublic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je weer emails van deze kring meer wilt ontvangen?.
        /// </summary>
        public static string ConfirmStartCircleEmails {
            get {
                return ResourceManager.GetString("ConfirmStartCircleEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je geen emails van deze kring meer wilt ontvangen?.
        /// </summary>
        public static string ConfirmStopCircleEmails {
            get {
                return ResourceManager.GetString("ConfirmStopCircleEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet u zeker dat u op {0} wil stemmen?.
        /// </summary>
        public static string ConfirmVoteAction {
            get {
                return ResourceManager.GetString("ConfirmVoteAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je deze postcode wilt verwijderen?.
        /// </summary>
        public static string ConfirmZipCodeDelete {
            get {
                return ResourceManager.GetString("ConfirmZipCodeDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je de {0} Zuiderlingen wilt overmaken?.
        /// </summary>
        public static string ConfirmZuiderlingTransaction {
            get {
                return ResourceManager.GetString("ConfirmZuiderlingTransaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact- en adresgegevens.
        /// </summary>
        public static string ContactAndAddress {
            get {
                return ResourceManager.GetString("ContactAndAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contactgegevens.
        /// </summary>
        public static string ContactInformation {
            get {
                return ResourceManager.GetString("ContactInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gesprekken.
        /// </summary>
        public static string Conversations {
            get {
                return ResourceManager.GetString("Conversations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteit aanmaken.
        /// </summary>
        public static string CreateActivity {
            get {
                return ResourceManager.GetString("CreateActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activiteiten aanmaken.
        /// </summary>
        public static string CreateBulkActivity {
            get {
                return ResourceManager.GetString("CreateBulkActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe feiten toevoegen.
        /// </summary>
        public static string CreateFact {
            get {
                return ResourceManager.GetString("CreateFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advertentie aanmaken.
        /// </summary>
        public static string CreateMarketplaceItem {
            get {
                return ResourceManager.GetString("CreateMarketplaceItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burenhulp aanbieden.
        /// </summary>
        public static string CreateNeighborhoodHelp {
            get {
                return ResourceManager.GetString("CreateNeighborhoodHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwsbericht aanmaken.
        /// </summary>
        public static string CreateNeighborhoodMessage {
            get {
                return ResourceManager.GetString("CreateNeighborhoodMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak een nieuw profiel aan.
        /// </summary>
        public static string CreateNewAccount {
            get {
                return ResourceManager.GetString("CreateNewAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe kring aanmaken.
        /// </summary>
        public static string CreateNewCircle {
            get {
                return ResourceManager.GetString("CreateNewCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maak een nieuwe taak aan.
        /// </summary>
        public static string CreateNewJob {
            get {
                return ResourceManager.GetString("CreateNewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegevens.
        /// </summary>
        public static string CreateNewJobDetails {
            get {
                return ResourceManager.GetString("CreateNewJobDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zichtbaarheid.
        /// </summary>
        public static string CreateNewJobVisibility {
            get {
                return ResourceManager.GetString("CreateNewJobVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuwe reactie plaatsen.
        /// </summary>
        public static string CreateReaction {
            get {
                return ResourceManager.GetString("CreateReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw onderwerp toevoegen.
        /// </summary>
        public static string CreateSubject {
            get {
                return ResourceManager.GetString("CreateSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum en tijd.
        /// </summary>
        public static string DateAndTime {
            get {
                return ResourceManager.GetString("DateAndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omschrijving.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string DetailInformation {
            get {
                return ResourceManager.GetString("DetailInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wijzig je kring.
        /// </summary>
        public static string EditCircle {
            get {
                return ResourceManager.GetString("EditCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feit bewerken.
        /// </summary>
        public static string EditFact {
            get {
                return ResourceManager.GetString("EditFact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taak aanpassen.
        /// </summary>
        public static string EditJob {
            get {
                return ResourceManager.GetString("EditJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beheer je organisatie.
        /// </summary>
        public static string EditOrganization {
            get {
                return ResourceManager.GetString("EditOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reactie bewerken.
        /// </summary>
        public static string EditReaction {
            get {
                return ResourceManager.GetString("EditReaction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onderwerp bewerken.
        /// </summary>
        public static string EditSubject {
            get {
                return ResourceManager.GetString("EditSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je e-mailadres is bevestigd..
        /// </summary>
        public static string EmailConfirmed {
            get {
                return ResourceManager.GetString("EmailConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail instellingen.
        /// </summary>
        public static string EmailSettings {
            get {
                return ResourceManager.GetString("EmailSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feiten.
        /// </summary>
        public static string Facts {
            get {
                return ResourceManager.GetString("Facts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Niet gevonden.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestanden.
        /// </summary>
        public static string Files {
            get {
                return ResourceManager.GetString("Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord vergeten?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algemene gegevens.
        /// </summary>
        public static string GeneralInformation {
            get {
                return ResourceManager.GetString("GeneralInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welkom bij LeeftSamen.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afbeeldingen.
        /// </summary>
        public static string Images {
            get {
                return ResourceManager.GetString("Images", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interne serverfout.
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introductiegegevens.
        /// </summary>
        public static string IntroductionInformation {
            get {
                return ResourceManager.GetString("IntroductionInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitnodigingen.
        /// </summary>
        public static string Invitations {
            get {
                return ResourceManager.GetString("Invitations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensen uitnodigen voor je activiteit.
        /// </summary>
        public static string InviteUsersToActivity {
            get {
                return ResourceManager.GetString("InviteUsersToActivity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensen uitnodigen voor je kring.
        /// </summary>
        public static string InviteUsersToCircle {
            get {
                return ResourceManager.GetString("InviteUsersToCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mensen uitnodigen voor je organisatie.
        /// </summary>
        public static string InviteUsersToOrganization {
            get {
                return ResourceManager.GetString("InviteUsersToOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anderen uitnodigen.
        /// </summary>
        public static string InviteUsersToWebsite {
            get {
                return ResourceManager.GetString("InviteUsersToWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waar moet het item getoond worden?.
        /// </summary>
        public static string ItemVisibility {
            get {
                return ResourceManager.GetString("ItemVisibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Taken.
        /// </summary>
        public static string Jobs {
            get {
                return ResourceManager.GetString("Jobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Laatste berichten.
        /// </summary>
        public static string LatestMessages {
            get {
                return ResourceManager.GetString("LatestMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locked out.
        /// </summary>
        public static string LockedOut {
            get {
                return ResourceManager.GetString("LockedOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanmelden.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meld je aan met je profiel.
        /// </summary>
        public static string LoginUsingYourAccount {
            get {
                return ResourceManager.GetString("LoginUsingYourAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beheer je profiel.
        /// </summary>
        public static string ManageAccount {
            get {
                return ResourceManager.GetString("ManageAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beheer het buurtplein.
        /// </summary>
        public static string ManageSquare {
            get {
                return ResourceManager.GetString("ManageSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vraag en aanbod.
        /// </summary>
        public static string Marketplace {
            get {
                return ResourceManager.GetString("Marketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maaltijden.
        /// </summary>
        public static string Meals {
            get {
                return ResourceManager.GetString("Meals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn uitnodigingen.
        /// </summary>
        public static string MyCircleInvites {
            get {
                return ResourceManager.GetString("MyCircleInvites", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn kringen.
        /// </summary>
        public static string MyCircles {
            get {
                return ResourceManager.GetString("MyCircles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn vraag en aanbod.
        /// </summary>
        public static string MyMarketplace {
            get {
                return ResourceManager.GetString("MyMarketplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn advertenties.
        /// </summary>
        public static string MyMarketplaceItems {
            get {
                return ResourceManager.GetString("MyMarketplaceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn buurt.
        /// </summary>
        public static string MyNeighborhood {
            get {
                return ResourceManager.GetString("MyNeighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mijn buurtpleinen.
        /// </summary>
        public static string MySquares {
            get {
                return ResourceManager.GetString("MySquares", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} beheerder.
        /// </summary>
        public static string NbrAdmin {
            get {
                return ResourceManager.GetString("NbrAdmin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} beheerders.
        /// </summary>
        public static string NbrAdmins {
            get {
                return ResourceManager.GetString("NbrAdmins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} persoon wil lid worden van deze kring.
        /// </summary>
        public static string NbrCircleJoinRequest {
            get {
                return ResourceManager.GetString("NbrCircleJoinRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} personen willen lid worden van deze kring.
        /// </summary>
        public static string NbrCircleJoinRequests {
            get {
                return ResourceManager.GetString("NbrCircleJoinRequests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kringlid.
        /// </summary>
        public static string NbrCircleMember {
            get {
                return ResourceManager.GetString("NbrCircleMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} kringleden.
        /// </summary>
        public static string NbrCircleMembers {
            get {
                return ResourceManager.GetString("NbrCircleMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} medewerker.
        /// </summary>
        public static string NbrOrganizationMember {
            get {
                return ResourceManager.GetString("NbrOrganizationMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} medewerkers.
        /// </summary>
        public static string NbrOrganizationMembers {
            get {
                return ResourceManager.GetString("NbrOrganizationMembers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buurtnieuws.
        /// </summary>
        public static string NeighborhoodMessages {
            get {
                return ResourceManager.GetString("NeighborhoodMessages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buurtinstellingen.
        /// </summary>
        public static string NeighborhoodSettings {
            get {
                return ResourceManager.GetString("NeighborhoodSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Burenhulp.
        /// </summary>
        public static string NeighbourHelp {
            get {
                return ResourceManager.GetString("NeighbourHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nieuw gesprek.
        /// </summary>
        public static string NewConversation {
            get {
                return ResourceManager.GetString("NewConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen activiteiten gevonden.
        /// </summary>
        public static string NoActivitiesFound {
            get {
                return ResourceManager.GetString("NoActivitiesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen advertenties gevonden.
        /// </summary>
        public static string NoMarketplaceItemsFound {
            get {
                return ResourceManager.GetString("NoMarketplaceItemsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen nieuwsberichten gevonden.
        /// </summary>
        public static string NoMessagesFound {
            get {
                return ResourceManager.GetString("NoMessagesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen notificaties gevonden.
        /// </summary>
        public static string NoNotificationsFound {
            get {
                return ResourceManager.GetString("NoNotificationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen organisaties gevonden.
        /// </summary>
        public static string NoOrganizationsFound {
            get {
                return ResourceManager.GetString("NoOrganizationsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen organisaties gevonden rond het thema {0}.
        /// </summary>
        public static string NoOrganizationsFoundTheme {
            get {
                return ResourceManager.GetString("NoOrganizationsFoundTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen resultaten gevonden voor &quot;{0}&quot;.
        /// </summary>
        public static string NoSearchResult {
            get {
                return ResourceManager.GetString("NoSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notificaties.
        /// </summary>
        public static string Notifications {
            get {
                return ResourceManager.GetString("Notifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er staat nog niets op je tijdlijn..
        /// </summary>
        public static string NoTimelineFound {
            get {
                return ResourceManager.GetString("NoTimelineFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Openstaande taak.
        /// </summary>
        public static string NumberOfUnassignedJob {
            get {
                return ResourceManager.GetString("NumberOfUnassignedJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Openstaande taken.
        /// </summary>
        public static string NumberOfUnassignedJobs {
            get {
                return ResourceManager.GetString("NumberOfUnassignedJobs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eén resultaat gevonden voor &quot;{0}&quot;.
        /// </summary>
        public static string OneSearchResult {
            get {
                return ResourceManager.GetString("OneSearchResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thema&apos;s.
        /// </summary>
        public static string OrganisationThemes {
            get {
                return ResourceManager.GetString("OrganisationThemes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} activiteitenoverzicht.
        /// </summary>
        public static string OrganizationActivityFeed {
            get {
                return ResourceManager.GetString("OrganizationActivityFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} berichtenoverzicht.
        /// </summary>
        public static string OrganizationMessagesFeed {
            get {
                return ResourceManager.GetString("OrganizationMessagesFeed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Producten toevoegen.
        /// </summary>
        public static string OrganizationProducts {
            get {
                return ResourceManager.GetString("OrganizationProducts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisaties.
        /// </summary>
        public static string Organizations {
            get {
                return ResourceManager.GetString("Organizations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diensten toevoegen.
        /// </summary>
        public static string OrganizationServices {
            get {
                return ResourceManager.GetString("OrganizationServices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je dit bericht wilt vastzetten?.
        /// </summary>
        public static string PinConfirmation {
            get {
                return ResourceManager.GetString("PinConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoe wil je (indien van toepassing) met jouw vraag geholpen worden?.
        /// </summary>
        public static string Preferences {
            get {
                return ResourceManager.GetString("Preferences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uw huidige profiel is niet toegestaan.
        /// </summary>
        public static string ProfileNotAllowed {
            get {
                return ResourceManager.GetString("ProfileNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openbare kringen.
        /// </summary>
        public static string PublicCircles {
            get {
                return ResourceManager.GetString("PublicCircles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Openbare kringen in mijn buurt.
        /// </summary>
        public static string PublicCirclesInMyNeighborhood {
            get {
                return ResourceManager.GetString("PublicCirclesInMyNeighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiel aanmaken.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreren.
        /// </summary>
        public static string RegisterHome {
            get {
                return ResourceManager.GetString("RegisterHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Definieer je buurt.
        /// </summary>
        public static string RegisterNeighborhood {
            get {
                return ResourceManager.GetString("RegisterNeighborhood", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreren: Nog één vraag.
        /// </summary>
        public static string RegisterPioneer {
            get {
                return ResourceManager.GetString("RegisterPioneer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreren, stap 1/3: Profiel aanmaken.
        /// </summary>
        public static string RegisterStep1 {
            get {
                return ResourceManager.GetString("RegisterStep1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreren, stap 2/3: Je adres.
        /// </summary>
        public static string RegisterStep2 {
            get {
                return ResourceManager.GetString("RegisterStep2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registreren, stap 3/3: Jouw buurt.
        /// </summary>
        public static string RegisterStep3 {
            get {
                return ResourceManager.GetString("RegisterStep3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profiel verwijderen.
        /// </summary>
        public static string RemoveAccount {
            get {
                return ResourceManager.GetString("RemoveAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je de beheerrechten van deze gebruiker in wilt trekken?.
        /// </summary>
        public static string RemoveMemberAdminRights {
            get {
                return ResourceManager.GetString("RemoveMemberAdminRights", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Misbruik melden.
        /// </summary>
        public static string ReportAbuse {
            get {
                return ResourceManager.GetString("ReportAbuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gerapporteerde reacties.
        /// </summary>
        public static string ReportedReactions {
            get {
                return ResourceManager.GetString("ReportedReactions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Organisatie aanvragen.
        /// </summary>
        public static string RequestOrganization {
            get {
                return ResourceManager.GetString("RequestOrganization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wachtwoord instellen.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoeken.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} resultaten gevonden voor &quot;{1}&quot;.
        /// </summary>
        public static string SearchResults {
            get {
                return ResourceManager.GetString("SearchResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer een kringlid.
        /// </summary>
        public static string SelectCircleMember {
            get {
                return ResourceManager.GetString("SelectCircleMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stuur een privébericht.
        /// </summary>
        public static string SendMessageToMarketplaceItemOwner {
            get {
                return ResourceManager.GetString("SendMessageToMarketplaceItemOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alleen je naam en profielfoto zijn voor de ontvanger zichtbaar..
        /// </summary>
        public static string SendMessageToMarketplaceItemOwnerSub {
            get {
                return ResourceManager.GetString("SendMessageToMarketplaceItemOwnerSub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delen.
        /// </summary>
        public static string Share {
            get {
                return ResourceManager.GetString("Share", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toon locatie bij deze advertentie.
        /// </summary>
        public static string Showlocation {
            get {
                return ResourceManager.GetString("Showlocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gegevens buurtplein.
        /// </summary>
        public static string SquareData {
            get {
                return ResourceManager.GetString("SquareData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informatiepagina buurtplein.
        /// </summary>
        public static string SquareInfo {
            get {
                return ResourceManager.GetString("SquareInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start een gesprek met:.
        /// </summary>
        public static string StartConversation {
            get {
                return ResourceManager.GetString("StartConversation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welkom bij LeeftSamen.
        /// </summary>
        public static string StartPage {
            get {
                return ResourceManager.GetString("StartPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spullen te koop.
        /// </summary>
        public static string StuffForSale {
            get {
                return ResourceManager.GetString("StuffForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spullen te leen.
        /// </summary>
        public static string StuffToBorrow {
            get {
                return ResourceManager.GetString("StuffToBorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het LeeftSamen-platform ontwikkelen we met elkaar.&lt;br /&gt;Heb je een verbetersuggestie of een idee voor de doorontwikkeling van het platform?&lt;br /&gt;Laat je suggestie of idee hier achter.&lt;br /&gt;Alvast heel hartelijk dank!.
        /// </summary>
        public static string SuggestionModalSubtitle {
            get {
                return ResourceManager.GetString("SuggestionModalSubtitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suggestie indienen.
        /// </summary>
        public static string SuggestionModalTitle {
            get {
                return ResourceManager.GetString("SuggestionModalTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout:.
        /// </summary>
        public static string SummaryError {
            get {
                return ResourceManager.GetString("SummaryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fouten:.
        /// </summary>
        public static string SummaryErrors {
            get {
                return ResourceManager.GetString("SummaryErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algemene voorwaarden.
        /// </summary>
        public static string TermsAndConditions {
            get {
                return ResourceManager.GetString("TermsAndConditions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weet je zeker dat je dit bericht wilt losmaken?.
        /// </summary>
        public static string UnpinConfirmation {
            get {
                return ResourceManager.GetString("UnpinConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welkom {0}!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heb je te veel gekookt? Of even geen tijd om zelf te koken? Deel of haal dan gemakkelijk een maaltijd bij jou in de buurt!.
        /// </summary>
        public static string WelcomeMarketplaceMeals {
            get {
                return ResourceManager.GetString("WelcomeMarketplaceMeals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vind je het leuk om af en toe iets voor een ander te doen, of kun je zelf wel een handje hulp gebruiken? Via Burenhulp kun je gemakkelijk hulp aanbieden of je buren om hulp vragen..
        /// </summary>
        public static string WelcomeMarketplaceNeighbourHelp {
            get {
                return ResourceManager.GetString("WelcomeMarketplaceNeighbourHelp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welkom op Vraag en Aanbod. U kunt advertenties toevoegen of doorzoeken..
        /// </summary>
        public static string WelcomeMarketplaceOverview {
            get {
                return ResourceManager.GetString("WelcomeMarketplaceOverview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welkom op de buurtmarktplaats. Hier kun je gemakkelijk spullen kopen of verkopen bij jou in de buurt..
        /// </summary>
        public static string WelcomeMarketplaceStuffForSale {
            get {
                return ResourceManager.GetString("WelcomeMarketplaceStuffForSale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leen gemakkelijk spullen van je buren of bied zelf iets aan..
        /// </summary>
        public static string WelcomeMarketplaceStuffToBorrow {
            get {
                return ResourceManager.GetString("WelcomeMarketplaceStuffToBorrow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Werkgebied.
        /// </summary>
        public static string WorkingArea {
            get {
                return ResourceManager.GetString("WorkingArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personen waarvan jij buddy bent.
        /// </summary>
        public static string YouAreBuddyOf {
            get {
                return ResourceManager.GetString("YouAreBuddyOf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Je hebt geen advertenties.
        /// </summary>
        public static string YouDontHaveMarketplaceItems {
            get {
                return ResourceManager.GetString("YouDontHaveMarketplaceItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personen die jouw buddy zijn..
        /// </summary>
        public static string YourBuddies {
            get {
                return ResourceManager.GetString("YourBuddies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuiderling koppelen.
        /// </summary>
        public static string ZuiderlingSettings {
            get {
                return ResourceManager.GetString("ZuiderlingSettings", resourceCulture);
            }
        }
    }
}
