// <auto-generated />
namespace LeeftSamen.Portal.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CirclePhotoAlbum : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CirclePhotoAlbum));
        
        string IMigrationMetadata.Id
        {
            get { return "201509280818383_CirclePhotoAlbum"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
