// <auto-generated />
namespace LeeftSamen.Portal.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TrackEdits : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TrackEdits));
        
        string IMigrationMetadata.Id
        {
            get { return "201602241037493_TrackEdits"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
