// <auto-generated />
namespace LeeftSamen.Portal.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ActivityCircle : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ActivityCircle));
        
        string IMigrationMetadata.Id
        {
            get { return "201606030727383_ActivityCircle"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
